using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PayCalc24.Contracts.Identity;
using PayCalc24.Contracts.PayrollCalculation;
using PayCalc24.Contracts.PayrollFunds;
using PayCalc24.Contracts.Organization;
using PayCalc24.Contracts.PayrollInput;
using PayCalc24.Infrastructure.MariaDb.Organization;

namespace PayCalc24.Infrastructure.MariaDb.PayrollFunds;

internal sealed class PayrollFundDefinitionRow { public PayrollFundDefinitionId Id{get;set;} public CompanyId CompanyId{get;set;} public string Code{get;set;}=""; }
internal sealed class PayrollFundVersionRow { public PayrollFundVersionId Id{get;set;} public PayrollFundDefinitionId DefinitionId{get;set;} public CompanyId CompanyId{get;set;} public int Revision{get;set;} public string Name{get;set;}=""; public string? Description{get;set;} public string FundType{get;set;}=""; public string ScopeType{get;set;}=""; public string? ScopeEntityType{get;set;} public Guid? ScopeEntityId{get;set;} public string SourceType{get;set;}=""; public decimal? FixedAmount{get;set;} public string? InputCode{get;set;} public Guid? FormulaDefinitionId{get;set;} public Guid? FormulaVersionId{get;set;} public string? FormulaChecksum{get;set;} public string AllocationMethod{get;set;}=""; public int DecimalScale{get;set;} public bool AllowDeficit{get;set;} public bool AllowReserve{get;set;} public decimal? MinCoverage{get;set;} public decimal? MaxCoverage{get;set;} public string? CurrencyCode{get;set;} public PayrollFundDefinitionId? ParentFundDefinitionId{get;set;} public DateOnly EffectiveFrom{get;set;} public DateOnly? EffectiveTo{get;set;} public string LifecycleStatus{get;set;}=""; public DateTimeOffset CreatedAt{get;set;} public Guid CreatedBy{get;set;} public DateTimeOffset? PublishedAt{get;set;} public Guid? PublishedBy{get;set;} }
internal sealed class PayrollFundAllocationResultRow { public FundAllocationResultId Id{get;set;} public CompanyId CompanyId{get;set;} public PayrollPeriodId PayrollPeriodId{get;set;} public PayrollCalculationSnapshotId SnapshotId{get;set;} public int SnapshotRevision{get;set;} public PayrollCalculationRunId? CalculationRunId{get;set;} public PayrollFundDefinitionId FundDefinitionId{get;set;} public PayrollFundVersionId FundVersionId{get;set;} public decimal AvailableFund{get;set;} public decimal EligibleDemand{get;set;} public decimal FundedAmount{get;set;} public decimal UnfundedAmount{get;set;} public decimal ReserveAmount{get;set;} public decimal RawCoverageRatio{get;set;} public decimal EffectiveFundingRatio{get;set;} public string AllocationMethod{get;set;}=""; public string ExecutionMode{get;set;}=""; public string EngineVersion{get;set;}=""; public string CorrelationId{get;set;}=""; public string? ScenarioId{get;set;} public string IdempotencyKey{get;set;}=""; public string SnapshotHash{get;set;}=""; public string SourceProvenanceJson{get;set;}=""; public string ExplainTraceJson{get;set;}=""; public string ResultHash{get;set;}=""; public DateTimeOffset CreatedAt{get;set;} }
internal sealed class PayrollFundMemberAllocationResultRow { public FundMemberAllocationResultId Id{get;set;} public FundAllocationResultId FundAllocationResultId{get;set;} public string RequirementReference{get;set;}=""; public Guid? PayrollSubjectId{get;set;} public Guid? PayComponentId{get;set;} public decimal RequestedAmount{get;set;} public decimal EligibleAmount{get;set;} public decimal AllocatedAmount{get;set;} public decimal Weight{get;set;} public int Priority{get;set;} public decimal? FloorAmount{get;set;} public decimal? TargetAmount{get;set;} public decimal? CapAmount{get;set;} public int AllocationSequence{get;set;} public string ProvenanceType{get;set;}=""; public string ProvenanceJson{get;set;}=""; public string ResultHash{get;set;}=""; }

internal sealed class PayrollFundDefinitionRowConfiguration:IEntityTypeConfiguration<PayrollFundDefinitionRow>{public void Configure(EntityTypeBuilder<PayrollFundDefinitionRow>b){b.ToTable("PayrollFundDefinitions");b.HasKey(x=>x.Id);b.Property(x=>x.Id).Uuid(x=>x.Value,PayrollFundDefinitionId.From);Mapping.Company(b);b.Property(x=>x.Code).HasMaxLength(64);b.HasIndex(x=>new{x.CompanyId,x.Code}).IsUnique();}}
internal sealed class PayrollFundVersionRowConfiguration:IEntityTypeConfiguration<PayrollFundVersionRow>{public void Configure(EntityTypeBuilder<PayrollFundVersionRow>b){b.ToTable("PayrollFundVersions");b.HasKey(x=>x.Id);b.Property(x=>x.Id).Uuid(x=>x.Value,PayrollFundVersionId.From);b.Property(x=>x.DefinitionId).Uuid(x=>x.Value,PayrollFundDefinitionId.From);Mapping.Company(b);b.Property(x=>x.FixedAmount).HasPrecision(28,8);b.Property(x=>x.MinCoverage).HasPrecision(28,8);b.Property(x=>x.MaxCoverage).HasPrecision(28,8);b.HasIndex(x=>new{x.DefinitionId,x.Revision}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.LifecycleStatus,x.EffectiveFrom,x.EffectiveTo});}}
internal sealed class PayrollFundAllocationResultRowConfiguration:IEntityTypeConfiguration<PayrollFundAllocationResultRow>{public void Configure(EntityTypeBuilder<PayrollFundAllocationResultRow>b){b.ToTable("PayrollFundAllocationResults");b.HasKey(x=>x.Id);b.Property(x=>x.Id).Uuid(x=>x.Value,FundAllocationResultId.From);Mapping.Company(b);b.Property(x=>x.SnapshotId).Uuid(x=>x.Value,PayrollCalculationSnapshotId.From);b.Property(x=>x.FundVersionId).Uuid(x=>x.Value,PayrollFundVersionId.From);foreach(var p in new[]{nameof(PayrollFundAllocationResultRow.AvailableFund),nameof(PayrollFundAllocationResultRow.EligibleDemand),nameof(PayrollFundAllocationResultRow.FundedAmount),nameof(PayrollFundAllocationResultRow.UnfundedAmount),nameof(PayrollFundAllocationResultRow.ReserveAmount),nameof(PayrollFundAllocationResultRow.RawCoverageRatio),nameof(PayrollFundAllocationResultRow.EffectiveFundingRatio)})b.Property<decimal>(p).HasPrecision(28,8);b.HasIndex(x=>new{x.CompanyId,x.SnapshotId,x.FundVersionId,x.ExecutionMode});b.HasIndex(x=>new{x.CompanyId,x.SnapshotId,x.IdempotencyKey}).IsUnique();}}
internal sealed class PayrollFundMemberAllocationResultRowConfiguration:IEntityTypeConfiguration<PayrollFundMemberAllocationResultRow>{public void Configure(EntityTypeBuilder<PayrollFundMemberAllocationResultRow>b){b.ToTable("PayrollFundMemberAllocationResults");b.HasKey(x=>x.Id);b.Property(x=>x.Id).Uuid(x=>x.Value,FundMemberAllocationResultId.From);b.Property(x=>x.FundAllocationResultId).Uuid(x=>x.Value,FundAllocationResultId.From);foreach(var p in new[]{nameof(PayrollFundMemberAllocationResultRow.RequestedAmount),nameof(PayrollFundMemberAllocationResultRow.EligibleAmount),nameof(PayrollFundMemberAllocationResultRow.AllocatedAmount),nameof(PayrollFundMemberAllocationResultRow.Weight),nameof(PayrollFundMemberAllocationResultRow.FloorAmount),nameof(PayrollFundMemberAllocationResultRow.TargetAmount),nameof(PayrollFundMemberAllocationResultRow.CapAmount)})b.Property<decimal?>(p).HasPrecision(28,8);b.HasIndex(x=>new{x.FundAllocationResultId,x.AllocationSequence});}}
