using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PayCalc24.Contracts.FormulaRepository;

namespace PayCalc24.Infrastructure.MariaDb.FormulaRepository;

internal abstract class CompanyRow { public Guid Id{get;set;} public Guid CompanyId{get;set;} }
internal sealed class FormulaDefinitionRow:CompanyRow { public string Code{get;set;}="";public string Name{get;set;}="";public string? Description{get;set;}public FormulaDataType ReturnType{get;set;}public FormulaScopeType ScopeType{get;set;}public bool IsActive{get;set;} }
internal sealed class FormulaVersionRow:CompanyRow { public Guid FormulaDefinitionId{get;set;}public int Revision{get;set;}public string ExpressionText{get;set;}="";public string? ExpressionAstJson{get;set;}public DateOnly EffectiveFrom{get;set;}public DateOnly? EffectiveTo{get;set;}public FormulaLifecycleStatus LifecycleStatus{get;set;}public string? Checksum{get;set;}public DateTimeOffset CreatedAt{get;set;}public Guid CreatedBy{get;set;}public DateTimeOffset? ValidatedAt{get;set;}public DateTimeOffset? TestedAt{get;set;}public DateTimeOffset? ApprovedAt{get;set;}public DateTimeOffset? PublishedAt{get;set;}public Guid? PublishedBy{get;set;}public DateTimeOffset? RetiredAt{get;set;} }
internal sealed class FormulaDependencyRow:CompanyRow { public Guid FormulaVersionId{get;set;}public FormulaDependencyType DependencyType{get;set;}public string ReferenceCode{get;set;}="";public Guid? ReferencedEntityId{get;set;}public bool IsRequired{get;set;}public int? Sequence{get;set;} }
internal sealed class FormulaTestCaseRow:CompanyRow { public Guid FormulaVersionId{get;set;}public string Name{get;set;}="";public string InputJson{get;set;}="";public FormulaDataType? ExpectedDataType{get;set;}public decimal? DecimalValue{get;set;}public long? IntegerValue{get;set;}public bool? BooleanValue{get;set;}public DateOnly? DateValue{get;set;}public string? TextValue{get;set;}public decimal? Tolerance{get;set;}public string? ExpectedDiagnosticCode{get;set;}public bool IsRequired{get;set;}public string? Status{get;set;} }
internal sealed class ParameterSetVersionRow:CompanyRow { public string Code{get;set;}="";public string Name{get;set;}="";public string? Description{get;set;}public int Revision{get;set;}public DateOnly EffectiveFrom{get;set;}public DateOnly? EffectiveTo{get;set;}public FormulaLifecycleStatus LifecycleStatus{get;set;} }
internal sealed class ParameterValueRow:CompanyRow { public Guid ParameterSetVersionId{get;set;}public string Code{get;set;}="";public string? Name{get;set;}public FormulaDataType DataType{get;set;}public decimal? DecimalValue{get;set;}public long? IntegerValue{get;set;}public bool? BooleanValue{get;set;}public DateOnly? DateValue{get;set;}public string? TextValue{get;set;}public string? UnitType{get;set;}public string? Description{get;set;}public int? DisplayOrder{get;set;} }
internal sealed class LookupTableVersionRow:CompanyRow { public string Code{get;set;}="";public string Name{get;set;}="";public string? Description{get;set;}public FormulaDataType KeyDataType{get;set;}public FormulaDataType ValueDataType{get;set;}public LookupMatchType MatchType{get;set;}public bool AllowRangeOverlap{get;set;}public int Revision{get;set;}public DateOnly EffectiveFrom{get;set;}public DateOnly? EffectiveTo{get;set;}public FormulaLifecycleStatus LifecycleStatus{get;set;} }
internal sealed class LookupRow:CompanyRow { public Guid LookupTableVersionId{get;set;}public int Sequence{get;set;}public decimal? KeyDecimal{get;set;}public decimal? LowerDecimal{get;set;}public decimal? UpperDecimal{get;set;}public string? KeyText{get;set;}public decimal? ResultDecimal{get;set;}public long? ResultInteger{get;set;}public bool? ResultBoolean{get;set;}public DateOnly? ResultDate{get;set;}public string? ResultText{get;set;}public string? Label{get;set;}public string? MetadataJson{get;set;} }
internal sealed class RuleSetVersionRow:CompanyRow { public string Code{get;set;}="";public string Name{get;set;}="";public string? Description{get;set;}public FormulaDataType ReturnType{get;set;}public FormulaScopeType ScopeType{get;set;}public int Revision{get;set;}public DateOnly EffectiveFrom{get;set;}public DateOnly? EffectiveTo{get;set;}public FormulaLifecycleStatus LifecycleStatus{get;set;}public bool StopOnMatch{get;set;} }
internal sealed class RuleRow:CompanyRow { public Guid RuleSetVersionId{get;set;}public int Priority{get;set;}public string? ConditionExpressionText{get;set;}public string ResultExpressionText{get;set;}="";public bool IsElse{get;set;}public string? Status{get;set;}public string? Description{get;set;} }

internal abstract class RowConfiguration<T>:IEntityTypeConfiguration<T> where T:CompanyRow
{ public abstract string Table{get;}public virtual void Configure(EntityTypeBuilder<T>b){b.ToTable(Table);b.HasKey(x=>x.Id);b.Property(x=>x.Id).HasConversion(x=>x.ToString("D"),x=>Guid.Parse(x)).HasColumnType("char(36)");b.Property(x=>x.CompanyId).HasConversion(x=>x.ToString("D"),x=>Guid.Parse(x)).HasColumnType("char(36)");}protected static void Code(PropertyBuilder<string> p)=>p.HasMaxLength(64).IsRequired();protected static void Decimal(PropertyBuilder<decimal?> p)=>p.HasPrecision(28,8);}
internal sealed class FormulaDefinitionRowConfiguration:RowConfiguration<FormulaDefinitionRow>{public override string Table=>"FormulaDefinitions";public override void Configure(EntityTypeBuilder<FormulaDefinitionRow>b){base.Configure(b);Code(b.Property(x=>x.Code));b.Property(x=>x.Name).HasMaxLength(256);b.HasIndex(x=>new{x.CompanyId,x.Code}).IsUnique();}}
internal sealed class FormulaVersionRowConfiguration:RowConfiguration<FormulaVersionRow>{public override string Table=>"FormulaVersions";public override void Configure(EntityTypeBuilder<FormulaVersionRow>b){base.Configure(b);b.Property(x=>x.ExpressionText).HasColumnType("longtext");b.Property(x=>x.ExpressionAstJson).HasColumnType("json");b.Property(x=>x.Checksum).HasMaxLength(64);b.HasIndex(x=>new{x.FormulaDefinitionId,x.Revision}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.EffectiveFrom,x.EffectiveTo,x.LifecycleStatus});}}
internal sealed class FormulaDependencyRowConfiguration:RowConfiguration<FormulaDependencyRow>{public override string Table=>"FormulaDependencies";public override void Configure(EntityTypeBuilder<FormulaDependencyRow>b){base.Configure(b);Code(b.Property(x=>x.ReferenceCode));b.HasIndex(x=>new{x.FormulaVersionId,x.DependencyType,x.ReferenceCode}).IsUnique();}}
internal sealed class FormulaTestCaseRowConfiguration:RowConfiguration<FormulaTestCaseRow>{public override string Table=>"FormulaTestCases";public override void Configure(EntityTypeBuilder<FormulaTestCaseRow>b){base.Configure(b);b.Property(x=>x.InputJson).HasColumnType("json");Decimal(b.Property(x=>x.DecimalValue));Decimal(b.Property(x=>x.Tolerance));b.HasIndex(x=>x.FormulaVersionId);}}
internal sealed class ParameterSetVersionRowConfiguration:RowConfiguration<ParameterSetVersionRow>{public override string Table=>"ParameterSetVersions";public override void Configure(EntityTypeBuilder<ParameterSetVersionRow>b){base.Configure(b);Code(b.Property(x=>x.Code));b.HasIndex(x=>new{x.CompanyId,x.Code,x.Revision}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.Code,x.EffectiveFrom,x.EffectiveTo});}}
internal sealed class ParameterValueRowConfiguration:RowConfiguration<ParameterValueRow>{public override string Table=>"ParameterValues";public override void Configure(EntityTypeBuilder<ParameterValueRow>b){base.Configure(b);Code(b.Property(x=>x.Code));Decimal(b.Property(x=>x.DecimalValue));b.HasIndex(x=>new{x.ParameterSetVersionId,x.Code}).IsUnique();}}
internal sealed class LookupTableVersionRowConfiguration:RowConfiguration<LookupTableVersionRow>{public override string Table=>"LookupTableVersions";public override void Configure(EntityTypeBuilder<LookupTableVersionRow>b){base.Configure(b);Code(b.Property(x=>x.Code));b.HasIndex(x=>new{x.CompanyId,x.Code,x.Revision}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.Code,x.EffectiveFrom,x.EffectiveTo});}}
internal sealed class LookupRowConfiguration:RowConfiguration<LookupRow>{public override string Table=>"LookupRows";public override void Configure(EntityTypeBuilder<LookupRow>b){base.Configure(b);Decimal(b.Property(x=>x.KeyDecimal));Decimal(b.Property(x=>x.LowerDecimal));Decimal(b.Property(x=>x.UpperDecimal));Decimal(b.Property(x=>x.ResultDecimal));b.HasIndex(x=>new{x.LookupTableVersionId,x.Sequence}).IsUnique();}}
internal sealed class RuleSetVersionRowConfiguration:RowConfiguration<RuleSetVersionRow>{public override string Table=>"RuleSetVersions";public override void Configure(EntityTypeBuilder<RuleSetVersionRow>b){base.Configure(b);Code(b.Property(x=>x.Code));b.HasIndex(x=>new{x.CompanyId,x.Code,x.Revision}).IsUnique();b.HasIndex(x=>new{x.CompanyId,x.Code,x.EffectiveFrom,x.EffectiveTo});}}
internal sealed class RuleRowConfiguration:RowConfiguration<RuleRow>{public override string Table=>"Rules";public override void Configure(EntityTypeBuilder<RuleRow>b){base.Configure(b);b.Property(x=>x.ConditionExpressionText).HasColumnType("longtext");b.Property(x=>x.ResultExpressionText).HasColumnType("longtext");b.HasIndex(x=>new{x.RuleSetVersionId,x.Priority}).IsUnique();}}
