<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\PayCalc24.Domain\PayCalc24.Domain.csproj" />
    <ProjectReference Include="..\..\PayCalc24.Contracts\PayCalc24.Contracts.csproj" />
    <ProjectReference Include="..\PayCalc24.FormulaEngine\PayCalc24.FormulaEngine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PayCalc24.ApplicationTests" />
  </ItemGroup>

</Project>
