using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1861
namespace PayCalc24.Infrastructure.MariaDb.Migrations;

public partial class Task07DynamicFormulaRepository:Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
CREATE TABLE FormulaDefinitions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,Name varchar(256) NOT NULL,Description varchar(1024) NULL,ReturnType int NOT NULL,ScopeType int NOT NULL,IsActive tinyint(1) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_FormulaDefinitions_Company_Code(CompanyId,Code));
CREATE TABLE FormulaVersions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,FormulaDefinitionId char(36) NOT NULL,Revision int NOT NULL,ExpressionText longtext NOT NULL,ExpressionAstJson json NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,LifecycleStatus int NOT NULL,Checksum char(64) NULL,CreatedAt datetime(6) NOT NULL,CreatedBy char(36) NOT NULL,ValidatedAt datetime(6) NULL,TestedAt datetime(6) NULL,ApprovedAt datetime(6) NULL,PublishedAt datetime(6) NULL,PublishedBy char(36) NULL,RetiredAt datetime(6) NULL,PRIMARY KEY(Id),UNIQUE KEY UX_FormulaVersions_Definition_Revision(FormulaDefinitionId,Revision),KEY IX_FormulaVersions_Effective(CompanyId,EffectiveFrom,EffectiveTo,LifecycleStatus),CONSTRAINT FK_FormulaVersions_Definition FOREIGN KEY(FormulaDefinitionId) REFERENCES FormulaDefinitions(Id));
CREATE TABLE FormulaDependencies (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,FormulaVersionId char(36) NOT NULL,DependencyType int NOT NULL,ReferenceCode varchar(64) NOT NULL,ReferencedEntityId char(36) NULL,IsRequired tinyint(1) NOT NULL,Sequence int NULL,PRIMARY KEY(Id),UNIQUE KEY UX_FormulaDependencies_Identity(FormulaVersionId,DependencyType,ReferenceCode),CONSTRAINT FK_FormulaDependencies_Version FOREIGN KEY(FormulaVersionId) REFERENCES FormulaVersions(Id));
CREATE TABLE FormulaTestCases (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,FormulaVersionId char(36) NOT NULL,Name varchar(256) NOT NULL,InputJson json NOT NULL,ExpectedDataType int NULL,DecimalValue decimal(28,8) NULL,IntegerValue bigint NULL,BooleanValue tinyint(1) NULL,DateValue date NULL,TextValue varchar(4000) NULL,Tolerance decimal(28,8) NULL,ExpectedDiagnosticCode varchar(128) NULL,IsRequired tinyint(1) NOT NULL,Status varchar(32) NULL,PRIMARY KEY(Id),KEY IX_FormulaTestCases_Version(FormulaVersionId),CONSTRAINT FK_FormulaTestCases_Version FOREIGN KEY(FormulaVersionId) REFERENCES FormulaVersions(Id));
CREATE TABLE ParameterSetVersions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,Name varchar(256) NOT NULL,Description varchar(1024) NULL,Revision int NOT NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,LifecycleStatus int NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_ParameterSets_Identity(CompanyId,Code,Revision),KEY IX_ParameterSets_Effective(CompanyId,Code,EffectiveFrom,EffectiveTo));
CREATE TABLE ParameterValues (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,ParameterSetVersionId char(36) NOT NULL,Code varchar(64) NOT NULL,Name varchar(256) NULL,DataType int NOT NULL,DecimalValue decimal(28,8) NULL,IntegerValue bigint NULL,BooleanValue tinyint(1) NULL,DateValue date NULL,TextValue varchar(4000) NULL,UnitType varchar(64) NULL,Description varchar(1024) NULL,DisplayOrder int NULL,PRIMARY KEY(Id),UNIQUE KEY UX_ParameterValues_Code(ParameterSetVersionId,Code),CONSTRAINT FK_ParameterValues_Set FOREIGN KEY(ParameterSetVersionId) REFERENCES ParameterSetVersions(Id));
CREATE TABLE LookupTableVersions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,Name varchar(256) NOT NULL,Description varchar(1024) NULL,KeyDataType int NOT NULL,ValueDataType int NOT NULL,MatchType int NOT NULL,AllowRangeOverlap tinyint(1) NOT NULL,Revision int NOT NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,LifecycleStatus int NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_LookupTables_Identity(CompanyId,Code,Revision),KEY IX_LookupTables_Effective(CompanyId,Code,EffectiveFrom,EffectiveTo));
CREATE TABLE LookupRows (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,LookupTableVersionId char(36) NOT NULL,Sequence int NOT NULL,KeyDecimal decimal(28,8) NULL,LowerDecimal decimal(28,8) NULL,UpperDecimal decimal(28,8) NULL,KeyText varchar(4000) NULL,ResultDecimal decimal(28,8) NULL,ResultInteger bigint NULL,ResultBoolean tinyint(1) NULL,ResultDate date NULL,ResultText varchar(4000) NULL,Label varchar(256) NULL,MetadataJson json NULL,PRIMARY KEY(Id),UNIQUE KEY UX_LookupRows_Sequence(LookupTableVersionId,Sequence),CONSTRAINT FK_LookupRows_Table FOREIGN KEY(LookupTableVersionId) REFERENCES LookupTableVersions(Id));
CREATE TABLE RuleSetVersions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,Name varchar(256) NOT NULL,Description varchar(1024) NULL,ReturnType int NOT NULL,ScopeType int NOT NULL,Revision int NOT NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,LifecycleStatus int NOT NULL,StopOnMatch tinyint(1) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_RuleSets_Identity(CompanyId,Code,Revision),KEY IX_RuleSets_Effective(CompanyId,Code,EffectiveFrom,EffectiveTo));
CREATE TABLE Rules (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,RuleSetVersionId char(36) NOT NULL,Priority int NOT NULL,ConditionExpressionText longtext NULL,ResultExpressionText longtext NOT NULL,IsElse tinyint(1) NOT NULL,Status varchar(32) NULL,Description varchar(1024) NULL,PRIMARY KEY(Id),UNIQUE KEY UX_Rules_Priority(RuleSetVersionId,Priority),CONSTRAINT FK_Rules_Set FOREIGN KEY(RuleSetVersionId) REFERENCES RuleSetVersions(Id));
""");
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        foreach(var table in new[]{"Rules","RuleSetVersions","LookupRows","LookupTableVersions","ParameterValues","ParameterSetVersions","FormulaTestCases","FormulaDependencies","FormulaVersions","FormulaDefinitions"})migrationBuilder.DropTable(table);
    }
}
