using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace PayCalc24.Infrastructure.MariaDb.Migrations;

public partial class Task12Attendance:Migration
{
 protected override void Up(MigrationBuilder migrationBuilder)=>migrationBuilder.Sql("""
CREATE TABLE AttendanceSourceDefinitions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,Name varchar(256) NOT NULL,SourceKind varchar(32) NOT NULL,ExternalSystem varchar(128) NULL,TimeZoneId varchar(128) NOT NULL,Active tinyint(1) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_AttendanceSource_Company_Code(CompanyId,Code));
CREATE TABLE AttendanceMappingVersions (Id char(36) NOT NULL,SourceId char(36) NOT NULL,CompanyId char(36) NOT NULL,Revision int NOT NULL,PublicationState varchar(16) NOT NULL,MappingJson json NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_AttendanceMapping_Source_Revision(SourceId,Revision),KEY IX_AttendanceMapping_Company_Source(CompanyId,SourceId));
CREATE TABLE AttendancePolicyDefinitions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_AttendancePolicy_Company_Code(CompanyId,Code));
CREATE TABLE AttendancePolicyVersions (Id char(36) NOT NULL,DefinitionId char(36) NOT NULL,CompanyId char(36) NOT NULL,Revision int NOT NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,PublicationState varchar(16) NOT NULL,RulesJson json NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_AttendancePolicy_Definition_Revision(DefinitionId,Revision),KEY IX_AttendancePolicy_Effective(CompanyId,EffectiveFrom,EffectiveTo,PublicationState));
CREATE TABLE AttendanceImportBatches (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,SourceId char(36) NOT NULL,MappingVersionId char(36) NOT NULL,PolicyVersionId char(36) NOT NULL,PayrollPeriodId char(36) NOT NULL,DateFrom date NOT NULL,DateTo date NOT NULL,Status varchar(16) NOT NULL,SourceReference varchar(512) NOT NULL,SourceFingerprint char(64) NOT NULL,IdempotencyKey varchar(128) NOT NULL,ImportedAt datetime(6) NOT NULL,ImportedBy char(36) NOT NULL,CorrelationId varchar(128) NOT NULL,RowCount int NOT NULL,AcceptedCount int NOT NULL,RejectedCount int NOT NULL,WarningCount int NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_AttendanceBatch_Idempotency(CompanyId,IdempotencyKey),KEY IX_AttendanceBatch_Source(CompanyId,SourceId,DateFrom,DateTo),KEY IX_AttendanceBatch_Fingerprint(CompanyId,SourceFingerprint));
CREATE TABLE AttendanceFacts (Id char(36) NOT NULL,BatchId char(36) NOT NULL,CompanyId char(36) NOT NULL,PayrollSubjectId char(36) NOT NULL,BusinessDate date NOT NULL,FactKind varchar(32) NOT NULL,Quantity decimal(28,8) NULL,Unit varchar(16) NOT NULL,BooleanValue tinyint(1) NULL,Code varchar(128) NULL,SourceRecordReference varchar(256) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_AttendanceFact_SourceRecord(BatchId,SourceRecordReference,FactKind),KEY IX_AttendanceFact_SubjectDate(CompanyId,PayrollSubjectId,BusinessDate),KEY IX_AttendanceFact_Batch(CompanyId,BatchId));
CREATE TABLE AttendanceDerivedInputProvenance (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,BatchId char(36) NOT NULL,AttendanceFactId char(36) NOT NULL,AttendancePolicyVersionId char(36) NOT NULL,PayrollInputLedgerEntryId char(36) NOT NULL,FormulaVersionId char(36) NULL,ParameterSetVersionId char(36) NULL,LookupTableVersionId char(36) NULL,RuleSetVersionId char(36) NULL,EvaluationDate date NOT NULL,ResultHash char(64) NOT NULL,PRIMARY KEY(Id),KEY IX_AttendanceProvenance_Batch(CompanyId,BatchId),KEY IX_AttendanceProvenance_Ledger(CompanyId,PayrollInputLedgerEntryId));
""");
 protected override void Down(MigrationBuilder migrationBuilder)=>migrationBuilder.Sql("DROP TABLE AttendanceDerivedInputProvenance; DROP TABLE AttendanceFacts; DROP TABLE AttendanceImportBatches; DROP TABLE AttendancePolicyVersions; DROP TABLE AttendancePolicyDefinitions; DROP TABLE AttendanceMappingVersions; DROP TABLE AttendanceSourceDefinitions;");
}
