using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace PayCalc24.Infrastructure.MariaDb.Migrations;
public partial class Task13Performance:Migration
{
 protected override void Up(MigrationBuilder migrationBuilder)=>migrationBuilder.Sql("""
CREATE TABLE KpiDefinitions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_KpiDefinition_Company_Code(CompanyId,Code));
CREATE TABLE KpiDefinitionVersions (Id char(36) NOT NULL,DefinitionId char(36) NOT NULL,CompanyId char(36) NOT NULL,Revision int NOT NULL,Name varchar(256) NOT NULL,Description varchar(1024) NULL,DataType varchar(16) NOT NULL,UnitType varchar(64) NOT NULL,Direction varchar(32) NOT NULL,MinValue decimal(28,8) NULL,TargetValue decimal(28,8) NULL,MaxValue decimal(28,8) NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,LifecycleStatus varchar(16) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_KpiVersion_Definition_Revision(DefinitionId,Revision),KEY IX_KpiVersion_Effective(CompanyId,EffectiveFrom,EffectiveTo,LifecycleStatus));
CREATE TABLE KpiAssignments (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,KpiDefinitionVersionId char(36) NOT NULL,ScopeType varchar(32) NOT NULL,PayrollSubjectId char(36) NULL,OrganizationUnitId char(36) NULL,PositionId char(36) NULL,JobGradeId char(36) NULL,OtherScopeId varchar(128) NULL,Weight decimal(28,8) NOT NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,Active tinyint(1) NOT NULL,ScoringFormulaVersionId char(36) NULL,ParameterSetVersionId char(36) NULL,LookupTableVersionId char(36) NULL,RuleSetVersionId char(36) NULL,PRIMARY KEY(Id),KEY IX_KpiAssignment_Scope(CompanyId,ScopeType,PayrollSubjectId,OrganizationUnitId,EffectiveFrom,EffectiveTo),KEY IX_KpiAssignment_Definition(CompanyId,KpiDefinitionVersionId));
CREATE TABLE KpiResults (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,KpiDefinitionVersionId char(36) NOT NULL,ScopeType varchar(32) NOT NULL,PayrollSubjectId char(36) NULL,OrganizationUnitId char(36) NULL,PeriodCode varchar(64) NOT NULL,PeriodFrom date NOT NULL,PeriodTo date NOT NULL,DataType varchar(16) NOT NULL,DecimalValue decimal(28,8) NULL,IntegerValue bigint NULL,BooleanValue tinyint(1) NULL,SourceType varchar(16) NOT NULL,SourceSystem varchar(128) NULL,SourceReference varchar(512) NULL,RecordedAt datetime(6) NOT NULL,RecordedBy char(36) NULL,CorrelationId varchar(128) NOT NULL,IdempotencyKey varchar(128) NULL,SupersedesResultId char(36) NULL,Fingerprint char(64) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_KpiResult_Idempotency(CompanyId,IdempotencyKey),UNIQUE KEY UX_KpiResult_Supersedes(SupersedesResultId),KEY IX_KpiResult_SubjectPeriod(CompanyId,PayrollSubjectId,PeriodFrom,PeriodTo),KEY IX_KpiResult_Source(CompanyId,SourceSystem,SourceReference));
CREATE TABLE PerformancePolicyDefinitions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PerformancePolicy_Company_Code(CompanyId,Code));
CREATE TABLE PerformancePolicyVersions (Id char(36) NOT NULL,DefinitionId char(36) NOT NULL,CompanyId char(36) NOT NULL,Revision int NOT NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,LifecycleStatus varchar(16) NOT NULL,WeightNormalization varchar(32) NOT NULL,OverallFormulaVersionId char(36) NULL,OutputsJson json NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PerformancePolicy_Revision(DefinitionId,Revision),KEY IX_PerformancePolicy_Effective(CompanyId,EffectiveFrom,EffectiveTo,LifecycleStatus));
CREATE TABLE PerformanceGates (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,PerformancePolicyVersionId char(36) NOT NULL,Code varchar(64) NOT NULL,Priority int NOT NULL,ConditionFormulaVersionId char(36) NULL,ConditionRuleSetVersionId char(36) NULL,EffectType varchar(16) NOT NULL,EffectValue decimal(28,8) NULL,ResultFormulaVersionId char(36) NULL,StopOnMatch tinyint(1) NOT NULL,Enabled tinyint(1) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PerformanceGate_Priority(PerformancePolicyVersionId,Priority),KEY IX_PerformanceGate_CompanyPolicy(CompanyId,PerformancePolicyVersionId));
CREATE TABLE PerformanceEvaluationResults (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,PayrollSubjectId char(36) NULL,ScopeType varchar(32) NOT NULL,PeriodCode varchar(64) NOT NULL,PeriodFrom date NOT NULL,PeriodTo date NOT NULL,PolicyVersionId char(36) NOT NULL,OverallAchievement decimal(28,8) NOT NULL,FinalAchievement decimal(28,8) NOT NULL,ExplainTraceJson json NOT NULL,ResultHash char(64) NOT NULL,EngineVersion varchar(32) NOT NULL,ExecutionMode varchar(16) NOT NULL,CorrelationId varchar(128) NOT NULL,FinalizedAt datetime(6) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PerformanceResult_Hash(CompanyId,ResultHash),KEY IX_PerformanceResult_SubjectPeriod(CompanyId,PayrollSubjectId,PeriodFrom,PeriodTo));
CREATE TABLE PerformanceEvaluationKpiDetails (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,PerformanceEvaluationResultId char(36) NOT NULL,KpiAssignmentId char(36) NOT NULL,KpiDefinitionVersionId char(36) NOT NULL,KpiResultId char(36) NOT NULL,MeasuredValue decimal(28,8) NOT NULL,Achievement decimal(28,8) NOT NULL,Weight decimal(28,8) NOT NULL,WeightedAchievement decimal(28,8) NOT NULL,PRIMARY KEY(Id),KEY IX_PerformanceDetail_Result(CompanyId,PerformanceEvaluationResultId),KEY IX_PerformanceDetail_Fact(CompanyId,KpiResultId));
CREATE TABLE PerformanceDerivedInputProvenance (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,PerformanceEvaluationResultId char(36) NOT NULL,PayrollInputLedgerEntryId char(36) NOT NULL,SourceKpiResultId char(36) NOT NULL,PerformancePolicyVersionId char(36) NOT NULL,GateIdsJson json NOT NULL,FormulaVersionIdsJson json NOT NULL,ParameterVersionIdsJson json NOT NULL,LookupVersionIdsJson json NOT NULL,RuleSetVersionIdsJson json NOT NULL,EvaluationBusinessDate date NOT NULL,ExecutionMode varchar(16) NOT NULL,ResultHash char(64) NOT NULL,PRIMARY KEY(Id),KEY IX_PerformanceProvenance_Result(CompanyId,PerformanceEvaluationResultId),KEY IX_PerformanceProvenance_Ledger(CompanyId,PayrollInputLedgerEntryId));
""");
 protected override void Down(MigrationBuilder migrationBuilder)=>migrationBuilder.Sql("DROP TABLE PerformanceDerivedInputProvenance; DROP TABLE PerformanceEvaluationKpiDetails; DROP TABLE PerformanceEvaluationResults; DROP TABLE PerformanceGates; DROP TABLE PerformancePolicyVersions; DROP TABLE PerformancePolicyDefinitions; DROP TABLE KpiResults; DROP TABLE KpiAssignments; DROP TABLE KpiDefinitionVersions; DROP TABLE KpiDefinitions;");
}
