using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable CA1861
namespace PayCalc24.Infrastructure.MariaDb.Migrations;

public partial class Task09PayrollPeriodSnapshots : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
CREATE TABLE PayrollPeriods (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,Name varchar(256) NULL,PeriodStart date NOT NULL,PeriodEnd date NOT NULL,BusinessDate date NOT NULL,PaymentDate date NULL,LifecycleStatus int NOT NULL,Revision bigint NOT NULL,CreatedAt datetime(6) NOT NULL,CreatedBy char(36) NOT NULL,UpdatedAt datetime(6) NULL,UpdatedBy char(36) NULL,PreparedAt datetime(6) NULL,PreparedBy char(36) NULL,FrozenAt datetime(6) NULL,FrozenBy char(36) NULL,CalculatedAt datetime(6) NULL,CalculatedBy char(36) NULL,ClosedAt datetime(6) NULL,ClosedBy char(36) NULL,ReopenedAt datetime(6) NULL,ReopenedBy char(36) NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PayrollPeriods_Company_Code(CompanyId,Code),UNIQUE KEY UX_PayrollPeriods_Company_Dates(CompanyId,PeriodStart,PeriodEnd),KEY IX_PayrollPeriods_Company_Status(CompanyId,LifecycleStatus));
CREATE TABLE PayrollPeriodLifecycleEvents (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,PayrollPeriodId char(36) NOT NULL,FromStatus int NULL,ToStatus int NOT NULL,PeriodRevision bigint NOT NULL,SnapshotRevision int NULL,Reason varchar(1024) NULL,OccurredAt datetime(6) NOT NULL,Actor char(36) NOT NULL,CorrelationId varchar(128) NOT NULL,PRIMARY KEY(Id),KEY IX_PayrollPeriodEvents_Period(CompanyId,PayrollPeriodId,OccurredAt),CONSTRAINT FK_PayrollPeriodEvents_Period FOREIGN KEY(PayrollPeriodId) REFERENCES PayrollPeriods(Id));
CREATE TABLE PayrollCalculationSnapshots (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,PayrollPeriodId char(36) NOT NULL,SnapshotRevision int NOT NULL,ExecutionMode int NOT NULL,BusinessDate date NOT NULL,CreatedAt datetime(6) NOT NULL,CreatedBy char(36) NOT NULL,FrozenAt datetime(6) NOT NULL,FrozenBy char(36) NOT NULL,PopulationHash char(64) NOT NULL,InputHash char(64) NOT NULL,ConfigurationHash char(64) NOT NULL,SnapshotHash char(64) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PayrollSnapshots_Period_Revision(PayrollPeriodId,SnapshotRevision),KEY IX_PayrollSnapshots_Company_Period(CompanyId,PayrollPeriodId),CONSTRAINT FK_PayrollSnapshots_Period FOREIGN KEY(PayrollPeriodId) REFERENCES PayrollPeriods(Id));
CREATE TABLE PayrollSnapshotSubjects (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,SnapshotId char(36) NOT NULL,PayrollSubjectId char(36) NOT NULL,EmployeeCode varchar(64) NOT NULL,PayrollAssignmentId char(36) NOT NULL,OrganizationUnitId char(36) NOT NULL,PositionId char(36) NULL,JobGradeId char(36) NULL,CompensationSchemeId char(36) NULL,AssignmentEffectiveFrom date NOT NULL,AssignmentEffectiveTo date NULL,EligibleDependentCount int NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PayrollSnapshotSubjects_Subject(SnapshotId,PayrollSubjectId),CONSTRAINT FK_PayrollSnapshotSubjects_Snapshot FOREIGN KEY(SnapshotId) REFERENCES PayrollCalculationSnapshots(Id));
CREATE TABLE PayrollSnapshotEligibleDependents (SnapshotSubjectId char(36) NOT NULL,EmployeeDependentId char(36) NOT NULL,PRIMARY KEY(SnapshotSubjectId,EmployeeDependentId),CONSTRAINT FK_PayrollSnapshotDependents_Subject FOREIGN KEY(SnapshotSubjectId) REFERENCES PayrollSnapshotSubjects(Id));
CREATE TABLE PayrollSnapshotInputs (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,SnapshotSubjectId char(36) NOT NULL,PayrollInputDefinitionId char(36) NOT NULL,DefinitionRevision int NOT NULL,Code varchar(64) NOT NULL,DataType int NOT NULL,UnitType int NOT NULL,AggregationType int NOT NULL,DecimalValue decimal(28,8) NULL,IntegerValue bigint NULL,BooleanValue tinyint(1) NULL,DateValue date NULL,TextValue varchar(4000) NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PayrollSnapshotInputs_Definition(SnapshotSubjectId,PayrollInputDefinitionId),CONSTRAINT FK_PayrollSnapshotInputs_Subject FOREIGN KEY(SnapshotSubjectId) REFERENCES PayrollSnapshotSubjects(Id));
CREATE TABLE PayrollSnapshotInputEntries (SnapshotInputId char(36) NOT NULL,PayrollInputLedgerEntryId char(36) NOT NULL,PRIMARY KEY(SnapshotInputId,PayrollInputLedgerEntryId),CONSTRAINT FK_PayrollSnapshotInputEntries_Input FOREIGN KEY(SnapshotInputId) REFERENCES PayrollSnapshotInputs(Id));
CREATE TABLE PayrollSnapshotCompensationVersions (SnapshotId char(36) NOT NULL,CompensationSchemeId char(36) NOT NULL,SchemeVersion int NOT NULL,PRIMARY KEY(SnapshotId,CompensationSchemeId));
CREATE TABLE PayrollSnapshotPayComponentVersions (SnapshotId char(36) NOT NULL,CompensationSchemeId char(36) NOT NULL,PayComponentId char(36) NOT NULL,ComponentVersion int NOT NULL,Sequence int NOT NULL,CalculationMethod int NOT NULL,FormulaDefinitionId char(36) NULL,PRIMARY KEY(SnapshotId,CompensationSchemeId,PayComponentId));
CREATE TABLE PayrollSnapshotFormulaVersions (SnapshotId char(36) NOT NULL,FormulaDefinitionId char(36) NOT NULL,FormulaVersionId char(36) NOT NULL,Revision int NOT NULL,Checksum char(64) NOT NULL,PRIMARY KEY(SnapshotId,FormulaDefinitionId),UNIQUE KEY UX_PayrollSnapshotFormula_Version(SnapshotId,FormulaVersionId));
CREATE TABLE PayrollSnapshotParameterVersions (SnapshotId char(36) NOT NULL,ParameterSetVersionId char(36) NOT NULL,Code varchar(64) NOT NULL,Revision int NOT NULL,PRIMARY KEY(SnapshotId,ParameterSetVersionId));
CREATE TABLE PayrollSnapshotLookupVersions (SnapshotId char(36) NOT NULL,LookupTableVersionId char(36) NOT NULL,Code varchar(64) NOT NULL,Revision int NOT NULL,PRIMARY KEY(SnapshotId,LookupTableVersionId));
CREATE TABLE PayrollSnapshotRuleSetVersions (SnapshotId char(36) NOT NULL,RuleSetVersionId char(36) NOT NULL,Code varchar(64) NOT NULL,Revision int NOT NULL,StopOnMatch tinyint(1) NOT NULL,PRIMARY KEY(SnapshotId,RuleSetVersionId));
""");
    }
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        foreach(var table in new[]{"PayrollSnapshotRuleSetVersions","PayrollSnapshotLookupVersions","PayrollSnapshotParameterVersions","PayrollSnapshotFormulaVersions","PayrollSnapshotPayComponentVersions","PayrollSnapshotCompensationVersions","PayrollSnapshotInputEntries","PayrollSnapshotInputs","PayrollSnapshotEligibleDependents","PayrollSnapshotSubjects","PayrollCalculationSnapshots","PayrollPeriodLifecycleEvents","PayrollPeriods"}) migrationBuilder.DropTable(table);
    }
}
