using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace PayCalc24.Infrastructure.MariaDb.Migrations;

public partial class Task11PayrollFunds:Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)=>migrationBuilder.Sql("""
CREATE TABLE PayrollFundDefinitions (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,Code varchar(64) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PayrollFundDefinitions_Company_Code(CompanyId,Code));
CREATE TABLE PayrollFundVersions (Id char(36) NOT NULL,DefinitionId char(36) NOT NULL,CompanyId char(36) NOT NULL,Revision int NOT NULL,Name varchar(256) NOT NULL,Description varchar(1024) NULL,FundType varchar(32) NOT NULL,ScopeType varchar(32) NOT NULL,ScopeEntityType varchar(64) NULL,ScopeEntityId char(36) NULL,SourceType varchar(32) NOT NULL,FixedAmount decimal(28,8) NULL,InputCode varchar(64) NULL,FormulaDefinitionId char(36) NULL,FormulaVersionId char(36) NULL,FormulaChecksum char(64) NULL,AllocationMethod varchar(32) NOT NULL,DecimalScale int NOT NULL,AllowDeficit tinyint(1) NOT NULL,AllowReserve tinyint(1) NOT NULL,MinCoverage decimal(28,8) NULL,MaxCoverage decimal(28,8) NULL,CurrencyCode varchar(3) NULL,ParentFundDefinitionId char(36) NULL,EffectiveFrom date NOT NULL,EffectiveTo date NULL,LifecycleStatus varchar(16) NOT NULL,CreatedAt datetime(6) NOT NULL,CreatedBy char(36) NOT NULL,PublishedAt datetime(6) NULL,PublishedBy char(36) NULL,PRIMARY KEY(Id),UNIQUE KEY UX_PayrollFundVersions_Definition_Revision(DefinitionId,Revision),KEY IX_PayrollFundVersions_Effective(CompanyId,LifecycleStatus,EffectiveFrom,EffectiveTo));
CREATE TABLE PayrollSnapshotFundVersions (SnapshotId char(36) NOT NULL,CompanyId char(36) NOT NULL,FundVersionId char(36) NOT NULL,FundDefinitionId char(36) NOT NULL,Revision int NOT NULL,Code varchar(64) NOT NULL,PolicyJson json NOT NULL,SourceJson json NOT NULL,PRIMARY KEY(SnapshotId,FundVersionId));
CREATE TABLE PayrollFundAllocationResults (Id char(36) NOT NULL,CompanyId char(36) NOT NULL,PayrollPeriodId char(36) NOT NULL,SnapshotId char(36) NOT NULL,SnapshotRevision int NOT NULL,CalculationRunId char(36) NULL,FundDefinitionId char(36) NOT NULL,FundVersionId char(36) NOT NULL,AvailableFund decimal(28,8) NOT NULL,EligibleDemand decimal(28,8) NOT NULL,FundedAmount decimal(28,8) NOT NULL,UnfundedAmount decimal(28,8) NOT NULL,ReserveAmount decimal(28,8) NOT NULL,RawCoverageRatio decimal(28,8) NOT NULL,EffectiveFundingRatio decimal(28,8) NOT NULL,AllocationMethod varchar(32) NOT NULL,ExecutionMode varchar(16) NOT NULL,EngineVersion varchar(32) NOT NULL,CorrelationId varchar(128) NOT NULL,ScenarioId varchar(128) NULL,IdempotencyKey varchar(128) NOT NULL,SnapshotHash char(64) NOT NULL,SourceProvenanceJson json NOT NULL,ExplainTraceJson json NOT NULL,ResultHash char(64) NOT NULL,CreatedAt datetime(6) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_FundAllocation_Idempotency(CompanyId,SnapshotId,IdempotencyKey),KEY IX_FundAllocation_Context(CompanyId,SnapshotId,FundVersionId,ExecutionMode));
CREATE TABLE PayrollFundMemberAllocationResults (Id char(36) NOT NULL,FundAllocationResultId char(36) NOT NULL,RequirementReference varchar(128) NOT NULL,PayrollSubjectId char(36) NULL,PayComponentId char(36) NULL,RequestedAmount decimal(28,8) NOT NULL,EligibleAmount decimal(28,8) NOT NULL,AllocatedAmount decimal(28,8) NOT NULL,Weight decimal(28,8) NOT NULL,Priority int NOT NULL,FloorAmount decimal(28,8) NULL,TargetAmount decimal(28,8) NULL,CapAmount decimal(28,8) NULL,AllocationSequence int NOT NULL,ProvenanceType varchar(32) NOT NULL,ProvenanceJson json NOT NULL,ResultHash char(64) NOT NULL,PRIMARY KEY(Id),UNIQUE KEY UX_FundMember_Requirement(FundAllocationResultId,RequirementReference),KEY IX_FundMember_Subject(FundAllocationResultId,PayrollSubjectId,PayComponentId));
""");
    protected override void Down(MigrationBuilder migrationBuilder)=>migrationBuilder.Sql("DROP TABLE PayrollFundMemberAllocationResults; DROP TABLE PayrollFundAllocationResults; DROP TABLE PayrollSnapshotFundVersions; DROP TABLE PayrollFundVersions; DROP TABLE PayrollFundDefinitions;");
}
