using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using PayCalc24.Contracts.Attendance;
using PayCalc24.Contracts.Diagnostics;
using PayCalc24.Contracts.Identity;
using PayCalc24.Contracts.Operations;
using PayCalc24.Contracts.Organization;
using PayCalc24.Contracts.PayrollInput;
using PayCalc24.Contracts.Temporal;

#pragma warning disable CA1725, CA1859, CS1998, CS8602, CS8603

namespace PayCalc24.Attendance.Services;

public sealed class AttendanceException(Diagnostic diagnostic):Exception(diagnostic.Code) { public Diagnostic Diagnostic { get; }=diagnostic; }

public sealed class AttendanceService(ICompanyContext companyContext,ICurrentUser currentUser,ICorrelationContext correlationContext,IAuditWriter auditWriter,TimeProvider timeProvider,IAttendancePayrollSubjectResolver subjectResolver,IPayrollInputDefinitionService inputDefinitions,IPayrollInputLedgerService ledger):IAttendanceService
{
    private sealed record Mapping(AttendanceMappingVersionDto Dto);
    private sealed record Policy(AttendancePolicyVersionDto Dto);
    private sealed class Batch(AttendanceImportBatchDto dto,AttendanceImportPreview preview)
    { public AttendanceImportBatchDto Dto { get; set; }=dto; public AttendanceImportPreview Preview { get; set; }=preview; public List<PayrollInputLedgerEntryDto> LedgerEntries { get; }=[]; }
    private readonly List<AttendanceSourceDto> sources=[]; private readonly List<Mapping> mappings=[]; private readonly List<Policy> policies=[]; private readonly List<Batch> batches=[]; private readonly Lock gate=new();

    public async ValueTask<AttendanceSourceDto> CreateSourceAsync(CompanyId c,string code,string name,AttendanceSourceKind kind,string timeZoneId,string? externalSystem=null,CancellationToken cancellationToken=default)
    { Scope(c); if(string.IsNullOrWhiteSpace(code)||string.IsNullOrWhiteSpace(name)||string.IsNullOrWhiteSpace(timeZoneId)) Fail(DiagnosticCodes.AttendanceInvalidMapping); try{_ = TimeZoneInfo.FindSystemTimeZoneById(timeZoneId);}catch(TimeZoneNotFoundException){Fail(DiagnosticCodes.AttendanceInvalidMapping,new(){["field"]="timeZoneId"});} lock(gate){var normalized=code.Trim();if(sources.Any(x=>x.CompanyId==c&&Eq(x.Code,normalized)))Fail(DiagnosticCodes.AttendanceInvalidMapping,new(){["field"]="sourceCode"});var dto=new AttendanceSourceDto(AttendanceSourceId.From(Guid.NewGuid()),c,normalized,name.Trim(),kind,Optional(externalSystem),timeZoneId,true);sources.Add(dto);Audit(c,"ATTENDANCE.SOURCE_CREATED","AttendanceSource",dto.Id.Value,cancellationToken).AsTask().GetAwaiter().GetResult();return dto;} }
    public async ValueTask<AttendanceMappingVersionDto> CreateMappingDraftAsync(CompanyId c,AttendanceSourceId sourceId,IReadOnlyList<AttendanceFieldMap> fields,CancellationToken cancellationToken=default)
    {Scope(c);Source(c,sourceId);ValidateMapping(fields);lock(gate){var dto=new AttendanceMappingVersionDto(AttendanceMappingVersionId.From(Guid.NewGuid()),sourceId,c,mappings.Count(x=>x.Dto.SourceId==sourceId)+1,PublicationState.DRAFT,fields.Select(x=>x with{CanonicalField=x.CanonicalField.Trim(),SourceField=x.SourceField.Trim()}).ToArray());mappings.Add(new(dto));Audit(c,"ATTENDANCE.MAPPING_DRAFT_CREATED","AttendanceMappingVersion",dto.Id.Value,cancellationToken).AsTask().GetAwaiter().GetResult();return dto;}}
    public async ValueTask<AttendanceMappingVersionDto> PublishMappingAsync(CompanyId c,AttendanceMappingVersionId id,CancellationToken cancellationToken=default)
    {Scope(c);lock(gate){var item=MappingFor(c,id);if(item.Dto.PublicationState!=PublicationState.DRAFT)Fail(DiagnosticCodes.AttendanceInvalidMapping);var dto=item.Dto with{PublicationState=PublicationState.PUBLISHED};mappings[mappings.IndexOf(item)]=new(dto);Audit(c,"ATTENDANCE.MAPPING_PUBLISHED","AttendanceMappingVersion",id.Value,cancellationToken).AsTask().GetAwaiter().GetResult();return dto;}}
    public async ValueTask<AttendancePolicyVersionDto> CreatePolicyDraftAsync(CompanyId c,string code,EffectivePeriod period,IReadOnlyList<AttendanceDerivedInputRule> rules,AttendancePolicyDefinitionId? definitionId=null,CancellationToken cancellationToken=default)
    {Scope(c);if(string.IsNullOrWhiteSpace(code)||period.EffectiveTo is not null&&period.EffectiveFrom>=period.EffectiveTo||rules.Count==0||rules.Any(x=>string.IsNullOrWhiteSpace(x.InputCode)||x.Factor<0))Fail(DiagnosticCodes.AttendancePolicyNotFound);lock(gate){var def=definitionId??AttendancePolicyDefinitionId.From(Guid.NewGuid());var existing=policies.Where(x=>x.Dto.DefinitionId==def).ToArray();if(existing.Any(x=>x.Dto.CompanyId!=c))Fail(DiagnosticCodes.AttendanceCrossCompanySubject);var dto=new AttendancePolicyVersionDto(AttendancePolicyVersionId.From(Guid.NewGuid()),def,c,code.Trim(),existing.Length==0?1:existing.Max(x=>x.Dto.Revision)+1,period,PublicationState.DRAFT,rules.ToArray());policies.Add(new(dto));Audit(c,"ATTENDANCE.POLICY_DRAFT_CREATED","AttendancePolicyVersion",dto.Id.Value,cancellationToken).AsTask().GetAwaiter().GetResult();return dto;}}
    public async ValueTask<AttendancePolicyVersionDto> PublishPolicyAsync(CompanyId c,AttendancePolicyVersionId id,CancellationToken cancellationToken=default)
    {Scope(c);lock(gate){var item=PolicyFor(c,id);if(item.Dto.PublicationState!=PublicationState.DRAFT)Fail(DiagnosticCodes.AttendancePublishedPolicyImmutable);if(policies.Any(x=>x!=item&&x.Dto.DefinitionId==item.Dto.DefinitionId&&Published(x.Dto.PublicationState)&&x.Dto.EffectivePeriod.Overlaps(item.Dto.EffectivePeriod)))Fail(DiagnosticCodes.AttendancePolicyAmbiguous);var dto=item.Dto with{PublicationState=PublicationState.PUBLISHED};policies[policies.IndexOf(item)]=new(dto);Audit(c,"ATTENDANCE.POLICY_PUBLISHED","AttendancePolicyVersion",id.Value,cancellationToken).AsTask().GetAwaiter().GetResult();return dto;}}
    public AttendancePolicyVersionDto ResolvePolicy(CompanyId c,string code,DateOnly date){Scope(c);var found=policies.Where(x=>x.Dto.CompanyId==c&&Eq(x.Dto.Code,code)&&Published(x.Dto.PublicationState)&&x.Dto.EffectivePeriod.Contains(date)).Select(x=>x.Dto).ToArray();if(found.Length==0)Fail(DiagnosticCodes.AttendancePolicyNotFound);if(found.Length>1)Fail(DiagnosticCodes.AttendancePolicyAmbiguous);return found[0];}

    public async ValueTask<AttendanceImportPreview> PreviewAsync(PreviewAttendanceImport command,CancellationToken cancellationToken=default)
    {
        Scope(command.CompanyId);if(command.DateFrom>command.DateTo)Fail(DiagnosticCodes.AttendanceInvalidBusinessDate);var source=Source(command.CompanyId,command.SourceId);var mapping=MappingFor(command.CompanyId,command.MappingVersionId).Dto;if(mapping.SourceId!=source.Id||mapping.PublicationState!=PublicationState.PUBLISHED)Fail(DiagnosticCodes.AttendanceInvalidMapping);
        var policy=command.PolicyVersionId is { } pinned?PolicyFor(command.CompanyId,pinned).Dto:ResolveSinglePolicy(command.CompanyId,command.DateFrom,command.DateTo);
        var fingerprint=Fingerprint(command,policy.Id);lock(gate){var existing=batches.SingleOrDefault(x=>x.Dto.CompanyId==command.CompanyId&&x.Dto.IdempotencyKey==command.IdempotencyKey);if(existing is not null){if(existing.Dto.SourceFingerprint!=fingerprint)Fail(DiagnosticCodes.AttendanceImportIdempotencyConflict);return existing.Preview;}}
        var batchId=AttendanceImportBatchId.From(Guid.NewGuid());var normalized=Normalize(command,mapping,batchId);var derived=EvaluateFacts(command.CompanyId,normalized.Facts,policy,normalized.Diagnostics);
        var preview=new AttendanceImportPreview(batchId,AttendanceImportStatus.DRAFT,fingerprint,normalized.Facts,derived,normalized.Diagnostics,normalized.Accepted,normalized.Rejected,normalized.Diagnostics.Count(x=>x.Severity==DiagnosticSeverity.Warning));
        var now=timeProvider.GetUtcNow();var dto=new AttendanceImportBatchDto(batchId,command.CompanyId,source.Id,mapping.Id,policy.Id,command.PayrollPeriodId,command.DateFrom,command.DateTo,AttendanceImportStatus.DRAFT,command.SourceReference,fingerprint,command.IdempotencyKey,now,currentUser.UserId,correlationContext.CorrelationId,command.Rows.Count,preview.AcceptedRows,preview.RejectedRows,preview.WarningCount);lock(gate)batches.Add(new(dto,preview));await Audit(command.CompanyId,"ATTENDANCE.IMPORT_PREVIEWED","AttendanceImportBatch",batchId.Value,cancellationToken);return preview;
    }
    public ValueTask<AttendanceImportPreview> ValidateAsync(CompanyId c,AttendanceImportBatchId id,CancellationToken cancellationToken=default){Scope(c);lock(gate){var b=BatchFor(c,id);if(b.Dto.Status==AttendanceImportStatus.COMMITTED)Fail(DiagnosticCodes.AttendanceBatchImmutable);var status=b.Preview.Diagnostics.Any(x=>x.Severity==DiagnosticSeverity.Error)?AttendanceImportStatus.FAILED:AttendanceImportStatus.VALIDATED;b.Dto=b.Dto with{Status=status};b.Preview=b.Preview with{Status=status};return ValueTask.FromResult(b.Preview);}}
    public async ValueTask<AttendanceCommitResult> CommitAsync(CommitAttendanceImport command,CancellationToken cancellationToken=default)
    {
        Scope(command.CompanyId);Batch b;lock(gate){b=BatchFor(command.CompanyId,command.BatchId);if(b.Dto.Status==AttendanceImportStatus.COMMITTED)return new(b.Dto,b.LedgerEntries.ToArray(),true);if(b.Preview.Diagnostics.Any(x=>x.Severity==DiagnosticSeverity.Error))Fail(DiagnosticCodes.AttendanceBlockingValidationFailed);b.Dto=b.Dto with{Status=AttendanceImportStatus.VALIDATED};}
        foreach(var candidate in b.Preview.DerivedInputs.OrderBy(x=>x.PayrollSubjectId.Value).ThenBy(x=>x.BusinessDate).ThenBy(x=>x.InputCode,StringComparer.Ordinal))
        {
            var provenance=$"batch={b.Dto.Id.Value:D};source={b.Dto.SourceId.Value:D};policy={candidate.PolicyVersionId.Value:D};facts={string.Join(',',candidate.FactIds.Select(x=>x.Value.ToString("D")).Order())};hash={candidate.ResultHash}";
            PayrollInputLedgerEntryDto entry;var key=$"attendance:{b.Dto.Id.Value:D}:{candidate.PayrollSubjectId.Value:D}:{candidate.BusinessDate:yyyyMMdd}:{candidate.InputCode}";
            if(command.SupersededEntries?.TryGetValue(CandidateKey(candidate),out var target)==true)entry=await ledger.CorrectAsync(new(command.CompanyId,target,candidate.Value,key,PayrollInputSourceType.ATTENDANCE,b.Dto.SourceId.Value.ToString("D"),provenance,CorrelationId:b.Dto.CorrelationId),cancellationToken);
            else entry=await ledger.SubmitAsync(new(command.CompanyId,candidate.PayrollSubjectId,b.Dto.PayrollPeriodId,candidate.BusinessDate,candidate.Value,PayrollInputSourceType.ATTENDANCE,key,InputCode:candidate.InputCode,SourceSystem:b.Dto.SourceId.Value.ToString("D"),SourceReference:provenance,EffectiveDate:candidate.BusinessDate,CorrelationId:b.Dto.CorrelationId),cancellationToken);b.LedgerEntries.Add(entry);
        }
        lock(gate){b.Dto=b.Dto with{Status=AttendanceImportStatus.COMMITTED};b.Preview=b.Preview with{Status=AttendanceImportStatus.COMMITTED};}await Audit(command.CompanyId,"ATTENDANCE.IMPORT_COMMITTED","AttendanceImportBatch",b.Dto.Id.Value,cancellationToken);return new(b.Dto,b.LedgerEntries.ToArray(),false);
    }
    public AttendanceImportPreview Evaluate(CompanyId c,AttendanceImportBatchId id,AttendancePolicyVersionId policyId){Scope(c);var b=BatchFor(c,id);var policy=PolicyFor(c,policyId).Dto;var diagnostics=new List<AttendanceDiagnostic>();return b.Preview with{DerivedInputs=EvaluateFacts(c,b.Preview.Facts,policy,diagnostics),Diagnostics=diagnostics};}
    public AttendanceImportBatchDto GetBatch(CompanyId c,AttendanceImportBatchId id){Scope(c);return BatchFor(c,id).Dto;}

    private (AttendanceCanonicalFact[] Facts,AttendanceDiagnostic[] Diagnostics,int Accepted,int Rejected) Normalize(PreviewAttendanceImport c,AttendanceMappingVersionDto mapping,AttendanceImportBatchId batchId)
    {var facts=new List<AttendanceCanonicalFact>();var ds=new List<AttendanceDiagnostic>();var seen=new HashSet<string>(StringComparer.Ordinal);var accepted=0;foreach(var row in c.Rows){if(!seen.Add(row.RowReference)){Add(DiagnosticCodes.AttendanceDuplicateSourceRecord,row.RowReference);continue;}var values=mapping.Fields.ToDictionary(x=>x.CanonicalField,x=>row.Values.TryGetValue(x.SourceField,out var v)?v:null,StringComparer.OrdinalIgnoreCase);if(mapping.Fields.Any(x=>x.Required&&string.IsNullOrWhiteSpace(values[x.CanonicalField]))){Add(DiagnosticCodes.AttendanceInvalidMapping,row.RowReference);continue;}PayrollSubjectId? subject=null;if(values.TryGetValue("payrollSubjectId",out var sid)&&Guid.TryParse(sid,out var guid))subject=PayrollSubjectId.From(guid);else if(values.TryGetValue("employeeCode",out var employee)&&!string.IsNullOrWhiteSpace(employee))subject=subjectResolver.ResolveByEmployeeCode(c.CompanyId,employee.Trim());if(subject is null){Add(DiagnosticCodes.AttendanceUnknownPayrollSubject,row.RowReference);continue;}if(subjectResolver.FindCompany(subject.Value)!=c.CompanyId){Add(DiagnosticCodes.AttendanceCrossCompanySubject,row.RowReference);continue;}if(!values.TryGetValue("businessDate",out var dateText)||!DateOnly.TryParseExact(dateText,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var date)||date<c.DateFrom||date>c.DateTo){Add(DiagnosticCodes.AttendanceInvalidBusinessDate,row.RowReference);continue;}if(!values.TryGetValue("kind",out var kindText)||!Enum.TryParse<AttendanceFactKind>(kindText,true,out var kind)){Add(DiagnosticCodes.AttendanceInvalidMapping,row.RowReference);continue;}values.TryGetValue("quantity",out var qText);decimal? quantity=null;decimal q=0;if(!string.IsNullOrWhiteSpace(qText)&&!decimal.TryParse(qText,NumberStyles.Number,CultureInfo.InvariantCulture,out q)){Add(DiagnosticCodes.AttendanceInvalidMapping,row.RowReference);continue;}else if(!string.IsNullOrWhiteSpace(qText))quantity=q;if(quantity<0){Add(DiagnosticCodes.AttendanceNegativeDuration,row.RowReference);continue;}values.TryGetValue("unit",out var unitText);if(!Enum.TryParse<AttendanceQuantityUnit>(unitText,true,out var unit)){Add(DiagnosticCodes.AttendanceInvalidMapping,row.RowReference);continue;}values.TryGetValue("code",out var code);facts.Add(new(AttendanceFactId.From(Guid.NewGuid()),c.CompanyId,subject.Value,date,kind,quantity,unit,unit==AttendanceQuantityUnit.BOOLEAN?quantity!=0:null,Optional(code),row.RowReference,batchId));accepted++;}return(facts.ToArray(),ds.ToArray(),accepted,c.Rows.Count-accepted);void Add(string code,string row)=>ds.Add(new(code,DiagnosticSeverity.Error,row,new Dictionary<string,object?>{{"rowReference",row}}));}
    private IReadOnlyList<AttendanceDerivedInputCandidate> EvaluateFacts(CompanyId c,IReadOnlyList<AttendanceCanonicalFact> facts,AttendancePolicyVersionDto policy,ICollection<AttendanceDiagnostic> ds)
    {var result=new List<AttendanceDerivedInputCandidate>();foreach(var group in facts.GroupBy(x=>new{x.PayrollSubjectId,x.BusinessDate})){foreach(var rule in policy.Rules){var selected=group.Where(x=>x.Kind==rule.FactKind&&x.Unit==rule.FactUnit).OrderBy(x=>x.SourceRecordReference,StringComparer.Ordinal).ThenBy(x=>x.Id.Value).ToArray();if(selected.Length==0)continue;PayrollInputDefinitionDto definition;try{definition=inputDefinitions.ResolveEffective(c,rule.InputCode,group.Key.BusinessDate);}catch(Exception){ds.Add(new(DiagnosticCodes.AttendancePayrollInputDefinitionNotFound,DiagnosticSeverity.Error,string.Join(',',selected.Select(x=>x.SourceRecordReference)),new Dictionary<string,object?>{{"inputCode",rule.InputCode}}));continue;}if(definition.Content.DataType!=rule.DataType){ds.Add(Diag(DiagnosticCodes.AttendancePayrollInputTypeMismatch));continue;}if(definition.Content.UnitType!=rule.InputUnit){ds.Add(Diag(DiagnosticCodes.AttendancePayrollInputUnitMismatch));continue;}var values=selected.Select(x=>x.Quantity??(x.BooleanValue==true?1m:0m)).ToArray();var number=rule.Aggregation switch{AttendanceAggregation.SUM=>values.Sum(),AttendanceAggregation.MIN=>values.Min(),AttendanceAggregation.MAX=>values.Max(),AttendanceAggregation.LATEST=>values[^1],_=>values.Sum()};number*=rule.Factor;var value=rule.DataType switch{PayrollInputDataType.DECIMAL=>PayrollInputValue.Decimal(number),PayrollInputDataType.INTEGER when number==decimal.Truncate(number)=>PayrollInputValue.Integer(decimal.ToInt64(number)),PayrollInputDataType.BOOLEAN=>PayrollInputValue.Boolean(number!=0),_=>null};if(value is null){ds.Add(Diag(DiagnosticCodes.AttendancePayrollInputTypeMismatch));continue;}var factIds=selected.Select(x=>x.Id).ToArray();var hash=Hash(string.Join('|',new[]{c.Value.ToString("D"),policy.Id.Value.ToString("D"),group.Key.PayrollSubjectId.Value.ToString("D"),group.Key.BusinessDate.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture),rule.InputCode,number.ToString(CultureInfo.InvariantCulture),string.Join(',',factIds.Select(x=>x.Value.ToString("D")).Order())}));result.Add(new(group.Key.PayrollSubjectId,group.Key.BusinessDate,rule.InputCode,value,rule.DataType,rule.InputUnit,policy.Id,factIds,hash,rule.FormulaVersionId,rule.ParameterSetVersionId,rule.LookupTableVersionId,rule.RuleSetVersionId));AttendanceDiagnostic Diag(string code)=>new(code,DiagnosticSeverity.Error,selected[0].SourceRecordReference,new Dictionary<string,object?>{{"inputCode",rule.InputCode}});}}return result;}
    private AttendancePolicyVersionDto ResolveSinglePolicy(CompanyId c,DateOnly from,DateOnly to){var found=policies.Where(x=>x.Dto.CompanyId==c&&Published(x.Dto.PublicationState)&&x.Dto.EffectivePeriod.Contains(from)&&x.Dto.EffectivePeriod.Contains(to)).Select(x=>x.Dto).ToArray();if(found.Length==0)Fail(DiagnosticCodes.AttendancePolicyNotFound);if(found.Length>1)Fail(DiagnosticCodes.AttendancePolicyAmbiguous);return found[0];}
    private AttendanceSourceDto Source(CompanyId c,AttendanceSourceId id){var any=sources.SingleOrDefault(x=>x.Id==id);if(any is null)Fail(DiagnosticCodes.AttendanceSourceNotFound);if(any.CompanyId!=c)Fail(DiagnosticCodes.AttendanceSourceNotFound);return any;}
    private Mapping MappingFor(CompanyId c,AttendanceMappingVersionId id){var any=mappings.SingleOrDefault(x=>x.Dto.Id==id);if(any is null||any.Dto.CompanyId!=c)Fail(DiagnosticCodes.AttendanceInvalidMapping);return any;}
    private Policy PolicyFor(CompanyId c,AttendancePolicyVersionId id){var any=policies.SingleOrDefault(x=>x.Dto.Id==id);if(any is null||any.Dto.CompanyId!=c)Fail(DiagnosticCodes.AttendancePolicyNotFound);return any;}
    private Batch BatchFor(CompanyId c,AttendanceImportBatchId id){var any=batches.SingleOrDefault(x=>x.Dto.Id==id);if(any is null||any.Dto.CompanyId!=c)Fail(DiagnosticCodes.AttendanceBatchNotFound);return any;}
    private static void ValidateMapping(IReadOnlyList<AttendanceFieldMap> fields){var names=fields.Select(x=>x.CanonicalField.Trim()).ToArray();if(fields.Count==0||fields.Any(x=>string.IsNullOrWhiteSpace(x.CanonicalField)||string.IsNullOrWhiteSpace(x.SourceField))||names.Distinct(StringComparer.OrdinalIgnoreCase).Count()!=names.Length||!names.Contains("businessDate",StringComparer.OrdinalIgnoreCase)||!names.Contains("kind",StringComparer.OrdinalIgnoreCase)||!names.Contains("unit",StringComparer.OrdinalIgnoreCase)||!names.Any(x=>x.Equals("employeeCode",StringComparison.OrdinalIgnoreCase)||x.Equals("payrollSubjectId",StringComparison.OrdinalIgnoreCase)))Fail(DiagnosticCodes.AttendanceInvalidMapping);}
    private static string Fingerprint(PreviewAttendanceImport c,AttendancePolicyVersionId p)=>Hash(string.Join('\n',new[]{c.CompanyId.Value.ToString("D"),c.SourceId.Value.ToString("D"),c.MappingVersionId.Value.ToString("D"),p.Value.ToString("D"),c.PayrollPeriodId.Value.ToString("D"),c.DateFrom.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture),c.DateTo.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture),c.SourceReference,string.Join('\n',c.Rows.OrderBy(x=>x.RowReference,StringComparer.Ordinal).Select(x=>$"{x.RowReference}|{string.Join(';',x.Values.OrderBy(v=>v.Key,StringComparer.Ordinal).Select(v=>$"{v.Key}={v.Value}"))}"))}));
    private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)));
    private static string CandidateKey(AttendanceDerivedInputCandidate c)=>$"{c.PayrollSubjectId.Value:D}|{c.BusinessDate:yyyy-MM-dd}|{c.InputCode}";
    private void Scope(CompanyId c){if(c!=companyContext.CompanyId)Fail(DiagnosticCodes.CompanyScopeMismatch);}
    private async ValueTask Audit(CompanyId c,string action,string entity,Guid id,CancellationToken token)=>await auditWriter.WriteAsync(new(c,currentUser.UserId,action,entity,id.ToString("D"),correlationContext.CorrelationId,timeProvider.GetUtcNow(),new Dictionary<string,object?>()),token);
    private static bool Published(PublicationState state)=>state is PublicationState.PUBLISHED or PublicationState.SUPERSEDED;private static bool Eq(string a,string b)=>StringComparer.OrdinalIgnoreCase.Equals(a.Trim(),b.Trim());private static string? Optional(string? s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim();private static void Fail(string code,Dictionary<string,object?>? args=null)=>throw new AttendanceException(new(code,DiagnosticSeverity.Error,args??new Dictionary<string,object?>()));
}
