<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PayCalc24.Application/PayCalc24.Application.csproj" />
    <ProjectReference Include="../../src/Modules/PayCalc24.Organization/PayCalc24.Organization.csproj" />
    <ProjectReference Include="../../src/Modules/PayCalc24.Compensation/PayCalc24.Compensation.csproj" />
    <ProjectReference Include="../../src/Modules/PayCalc24.PayrollInput/PayCalc24.PayrollInput.csproj" />
    <ProjectReference Include="..\..\src\Modules\PayCalc24.FormulaRepository\PayCalc24.FormulaRepository.csproj" />
    <ProjectReference Include="..\..\src\Modules\PayCalc24.FormulaEngine\PayCalc24.FormulaEngine.csproj" />
    <ProjectReference Include="..\..\src\Modules\PayCalc24.PayrollCalculation\PayCalc24.PayrollCalculation.csproj" />
    <ProjectReference Include="..\..\src\Modules\PayCalc24.PayrollFunds\PayCalc24.PayrollFunds.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
