using System.Globalization;
using PayCalc24.Contracts.Diagnostics;
using PayCalc24.Contracts.Identity;
using PayCalc24.Contracts.Operations;
using PayCalc24.Contracts.Organization;
using PayCalc24.Contracts.PayrollInput;
using PayCalc24.Contracts.Temporal;
using PayCalc24.PayrollInput.Model;
using PayCalc24.PayrollInput.Services;

namespace PayCalc24.ApplicationTests;

public sealed class Task06PayrollInputTests
{
    private static readonly DateOnly Jan1=new(2027,1,1),Jul1=new(2027,7,1);

    [Fact] public async Task DefinitionDraftPublicationAndHistoricalResolutionWork(){var f=new Fixture();var d=await f.Define("KPI_SCORE",PayrollInputDataType.DECIMAL);await f.Definitions.PublishAsync(f.Company,d.Id,1);f.Definitions.Close(f.Company,d.Id,1,Jul1);await f.Definitions.CreateDraftAsync(f.Company,d.Id,new(Jul1,null),f.Content("KPI_SCORE",PayrollInputDataType.DECIMAL)with{UnitType=PayrollInputUnitType.SCORE});await f.Definitions.PublishAsync(f.Company,d.Id,2);Assert.Equal(1,f.Definitions.ResolveEffective(f.Company,"KPI_SCORE",Jan1).Revision);Assert.Equal(2,f.Definitions.ResolveEffective(f.Company,"KPI_SCORE",Jul1).Revision);}
    [Fact] public async Task DuplicateCodeIsRejectedWithinCompanyButIndependentCompaniesMayUseIt(){var a=new Fixture();await a.Define("DAYS");var ex=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await a.Define("days"));Assert.Equal(DiagnosticCodes.DuplicateInputDefinitionCode,ex.Diagnostic.Code);var b=new Fixture();Assert.Equal("DAYS",(await b.Define("DAYS")).Content.Code);}
    [Fact] public async Task DraftCanChangeButPublishedDefinitionIsImmutable(){var f=new Fixture();var d=await f.Define("DAYS");var changed=await f.Definitions.UpdateDraftAsync(f.Company,d.Id,1,new(Jan1,null),d.Content with{Name="Changed"});Assert.Equal("Changed",changed.Content.Name);await f.Definitions.PublishAsync(f.Company,d.Id,1);var ex=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Definitions.UpdateDraftAsync(f.Company,d.Id,1,new(Jan1,null),d.Content));Assert.Equal(DiagnosticCodes.PublishedInputDefinitionImmutable,ex.Diagnostic.Code);}

    [Theory]
    [MemberData(nameof(TypedValues))]
    public async Task AllCanonicalTypedValuesAreAccepted(PayrollInputDataType type,PayrollInputValue value){var f=new Fixture();var d=await f.Published(type.ToString(),type);var entry=await f.Submit(d,value,"typed-"+type);Assert.Equal(type,entry.Value.DataType);}
    public static TheoryData<PayrollInputDataType,PayrollInputValue> TypedValues()=>new(){ {PayrollInputDataType.DECIMAL,PayrollInputValue.Decimal(12345678901234567890.12345678m)}, {PayrollInputDataType.INTEGER,PayrollInputValue.Integer(42)}, {PayrollInputDataType.BOOLEAN,PayrollInputValue.Boolean(true)}, {PayrollInputDataType.DATE,PayrollInputValue.Date(new(2027,1,31))}, {PayrollInputDataType.TEXT,PayrollInputValue.Text("canonical")}};
    [Fact] public async Task MismatchedTypeAndRangeAreRejected(){var f=new Fixture();var d=await f.Published("SCORE",PayrollInputDataType.DECIMAL,validation:new(0,100));var type=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Submit(d,PayrollInputValue.Integer(10),"type"));Assert.Equal(DiagnosticCodes.InvalidPayrollInputValueType,type.Diagnostic.Code);var range=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Submit(d,PayrollInputValue.Decimal(101),"range"));Assert.Equal(DiagnosticCodes.PayrollInputValueOutOfRange,range.Diagnostic.Code);}
    [Fact] public async Task DecimalPrecisionIsPreservedExactly(){var f=new Fixture();var d=await f.Published("AMOUNT",PayrollInputDataType.DECIMAL);const decimal expected=99999999999999999999.12345678m;var actual=await f.Submit(d,PayrollInputValue.Decimal(expected),"precision");Assert.Equal(expected,actual.Value.DecimalValue);}

    [Fact] public async Task SubjectCompanyIsolationIsEnforced(){var f=new Fixture();var d=await f.Published("DAYS");var foreign=PayrollSubjectId.From(Guid.NewGuid());f.Subjects.Owners[foreign]=CompanyId.From(Guid.NewGuid());var ex=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Ledger.SubmitAsync(f.Command(d,PayrollInputValue.Decimal(1),"foreign")with{PayrollSubjectId=foreign}));Assert.Equal(DiagnosticCodes.CrossCompanyPayrollSubject,ex.Diagnostic.Code);}
    [Fact] public async Task ManualAndExternalPoliciesAreEnforced(){var f=new Fixture();var noManual=await f.Published("API_ONLY",allowManual:false);var manual=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Submit(noManual,PayrollInputValue.Decimal(1),"manual"));Assert.Equal(DiagnosticCodes.ManualPayrollInputNotAllowed,manual.Diagnostic.Code);var noExternal=await f.Published("MANUAL_ONLY",allowExternal:false);var external=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Ledger.SubmitAsync(f.Command(noExternal,PayrollInputValue.Decimal(1),"external")with{SourceType=PayrollInputSourceType.API}));Assert.Equal(DiagnosticCodes.ExternalPayrollInputNotAllowed,external.Diagnostic.Code);}
    [Fact] public async Task ManualAndExternalUseTheSameCanonicalLedger(){var f=new Fixture();var d=await f.Published("VALUE");var manual=await f.Submit(d,PayrollInputValue.Decimal(1),"manual");var external=await f.Ledger.SubmitAsync(f.Command(d,PayrollInputValue.Decimal(2),"external")with{SourceType=PayrollInputSourceType.API,SourceSystem="TEST_API"});Assert.Equal(manual.InputDefinitionId,external.InputDefinitionId);Assert.Equal(2,f.Ledger.GetHistory(f.Company,f.Subject,f.Period,d.Id).Count);}

    [Fact] public async Task IdenticalRetryReturnsExistingEntryAndConflictIsRejected(){var f=new Fixture();var d=await f.Published("DAYS");var first=await f.Submit(d,PayrollInputValue.Decimal(20),"same");var retry=await f.Submit(d,PayrollInputValue.Decimal(20),"same");Assert.Equal(first.Id,retry.Id);Assert.Single(f.Ledger.GetHistory(f.Company,f.Subject,f.Period));var ex=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Submit(d,PayrollInputValue.Decimal(21),"same"));Assert.Equal(DiagnosticCodes.DuplicatePayrollInputIdempotencyKey,ex.Diagnostic.Code);}
    [Fact] public async Task CorrectionAppendsPreservesOriginalAndChangesEffectiveView(){var f=new Fixture();var d=await f.Published("ACTUAL_WORKING_DAYS");var original=await f.Submit(d,PayrollInputValue.Decimal(20),"v1");var correction=await f.Ledger.CorrectAsync(new(f.Company,original.Id,PayrollInputValue.Decimal(21),"v2"));var history=f.Ledger.GetHistory(f.Company,f.Subject,f.Period,d.Id);Assert.Equal(2,history.Count);Assert.Equal(20,history[0].Value.DecimalValue);Assert.Equal(original.Id,correction.SupersedesEntryId);Assert.Equal(21,f.Ledger.GetEffectiveInput(f.Company,f.Subject,f.Period,d.Id).Value.DecimalValue);Assert.Equal(2,f.Audit.Entries.Count(x=>x.ActionCode.StartsWith("PAYROLL_INPUT.LEDGER",StringComparison.Ordinal)));}
    [Fact] public async Task UnknownAndAlreadySupersededTargetsAreRejected(){var f=new Fixture();var unknown=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Ledger.CorrectAsync(new(f.Company,PayrollInputLedgerEntryId.From(Guid.NewGuid()),PayrollInputValue.Decimal(1),"x")));Assert.Equal(DiagnosticCodes.SupersededPayrollInputNotFound,unknown.Diagnostic.Code);var d=await f.Published("DAYS");var a=await f.Submit(d,PayrollInputValue.Decimal(1),"a");await f.Ledger.CorrectAsync(new(f.Company,a.Id,PayrollInputValue.Decimal(2),"b"));var branch=await Assert.ThrowsAsync<PayrollInputValidationException>(async()=>await f.Ledger.CorrectAsync(new(f.Company,a.Id,PayrollInputValue.Decimal(3),"c")));Assert.Equal(DiagnosticCodes.InvalidPayrollInputSupersessionScope,branch.Diagnostic.Code);}

    [Fact] public async Task SumAndAverageAggregationAreDeterministic(){var f=new Fixture();var sum=await f.Published("OT_HOURS",aggregation:PayrollInputAggregationType.SUM);await f.Submit(sum,PayrollInputValue.Decimal(2),"s1");await f.Submit(sum,PayrollInputValue.Decimal(3),"s2");await f.Submit(sum,PayrollInputValue.Decimal(1.5m),"s3");Assert.Equal(6.5m,f.Ledger.GetEffectiveInput(f.Company,f.Subject,f.Period,sum.Id).Value.DecimalValue);var avg=await f.Published("SCORE",aggregation:PayrollInputAggregationType.AVERAGE);await f.Submit(avg,PayrollInputValue.Decimal(80),"a1");await f.Submit(avg,PayrollInputValue.Decimal(100),"a2");Assert.Equal(90m,f.Ledger.GetEffectiveInput(f.Company,f.Subject,f.Period,avg.Id).Value.DecimalValue);}
    [Fact] public async Task NoneAggregationNeverSilentlyChoosesARecord(){var f=new Fixture();var d=await f.Published("VALUE");await f.Submit(d,PayrollInputValue.Decimal(1),"one");await f.Submit(d,PayrollInputValue.Decimal(2),"two");var ex=Assert.Throws<PayrollInputValidationException>(()=>f.Ledger.GetEffectiveInput(f.Company,f.Subject,f.Period,d.Id));Assert.Equal(DiagnosticCodes.AmbiguousActivePayrollInput,ex.Diagnostic.Code);}
    [Fact] public async Task SourceTraceIsPreserved(){var f=new Fixture();var d=await f.Published("ATTENDANCE");var e=await f.Ledger.SubmitAsync(f.Command(d,PayrollInputValue.Decimal(21),"trace")with{SourceType=PayrollInputSourceType.ATTENDANCE,SourceSystem="TEST_ATTENDANCE",SourceReference="ATT-001"});var trace=f.Ledger.GetSourceTrace(f.Company,e.Id);Assert.Equal("TEST_ATTENDANCE",trace.SourceSystem);Assert.Equal("ATT-001",trace.SourceReference);}

    [Theory][InlineData("en-US")][InlineData("vi-VN")]
    public async Task CultureDoesNotChangeCanonicalIdentityValueOrResolution(string culture){var old=CultureInfo.CurrentCulture;try{CultureInfo.CurrentCulture=new(culture);var f=new Fixture();var d=await f.Published("KPI_SCORE");var e=await f.Submit(d,PayrollInputValue.Decimal(92.5m),"culture");var effective=f.Ledger.GetEffectiveInputSet(f.Company,f.Subject,f.Period).Single();Assert.Equal("KPI_SCORE",effective.InputCode);Assert.Equal(92.5m,effective.Value.DecimalValue);Assert.Equal(e.Id,effective.ContributingEntryIds.Single());}finally{CultureInfo.CurrentCulture=old;}}
    [Fact] public async Task ArbitraryCompanyCodesUseExactlyTheSamePipeline(){var a=new Fixture();foreach(var item in new[]{("ACTUAL_WORKING_DAYS",21m),("OT_HOURS",5.5m),("KPI_SCORE",92m)}){var d=await a.Published(item.Item1);await a.Submit(d,PayrollInputValue.Decimal(item.Item2),"a-"+item.Item1);}var b=new Fixture();foreach(var item in new[]{("DAYS_PRESENT",22m),("EXTRA_TIME",3m),("PERFORMANCE_INDEX",.85m)}){var d=await b.Published(item.Item1);await b.Submit(d,PayrollInputValue.Decimal(item.Item2),"b-"+item.Item1);}Assert.Equal(3,a.Ledger.GetEffectiveInputSet(a.Company,a.Subject,a.Period).Count);Assert.Equal(3,b.Ledger.GetEffectiveInputSet(b.Company,b.Subject,b.Period).Count);}
    [Fact] public void LedgerEntityExposesNoBusinessMutationOrDeleteApi(){var methods=typeof(PayrollInputLedgerEntry).GetMethods().Select(x=>x.Name);Assert.DoesNotContain(methods,x=>x.Contains("Update",StringComparison.OrdinalIgnoreCase)||x.Contains("Delete",StringComparison.OrdinalIgnoreCase)||x.Contains("SetValue",StringComparison.OrdinalIgnoreCase));Assert.DoesNotContain(typeof(PayrollInputLedgerService).Assembly.GetTypes(),x=>x.Name.Contains("Formula",StringComparison.OrdinalIgnoreCase));}

    private sealed class Fixture
    {
        public CompanyId Company{get;}=CompanyId.From(Guid.NewGuid());public PayrollSubjectId Subject{get;}=PayrollSubjectId.From(Guid.NewGuid());public PayrollPeriodId Period{get;}=PayrollPeriodId.From(Guid.NewGuid());public SubjectReader Subjects{get;}=new();public AuditWriter Audit{get;}=new();public PayrollInputDefinitionService Definitions{get;}public PayrollInputLedgerService Ledger{get;}
        public Fixture(){Subjects.Owners[Subject]=Company;var context=new Context(Company);var user=new User();var correlation=new Correlation();Definitions=new(context,user,correlation,Audit,TimeProvider.System);Ledger=new(context,Subjects,Definitions,user,correlation,Audit,TimeProvider.System);}
        public PayrollInputDefinitionContent Content(string code,PayrollInputDataType type=PayrollInputDataType.DECIMAL,PayrollInputAggregationType aggregation=PayrollInputAggregationType.NONE,bool allowManual=true,bool allowExternal=true,PayrollInputValidation? validation=null)=>new(code,"Name "+code,null,type,PayrollInputUnitType.NONE,PayrollInputSourceType.OTHER,aggregation,false,allowManual,allowExternal,true,validation,10,PayrollInputDefinitionStatus.ACTIVE);
        public ValueTask<PayrollInputDefinitionDto> Define(string code,PayrollInputDataType type=PayrollInputDataType.DECIMAL,PayrollInputAggregationType aggregation=PayrollInputAggregationType.NONE,bool allowManual=true,bool allowExternal=true,PayrollInputValidation? validation=null)=>Definitions.CreateDraftAsync(Company,PayrollInputDefinitionId.From(Guid.NewGuid()),new(Jan1,null),Content(code,type,aggregation,allowManual,allowExternal,validation));
        public async ValueTask<PayrollInputDefinitionDto> Published(string code,PayrollInputDataType type=PayrollInputDataType.DECIMAL,PayrollInputAggregationType aggregation=PayrollInputAggregationType.NONE,bool allowManual=true,bool allowExternal=true,PayrollInputValidation? validation=null){var d=await Define(code,type,aggregation,allowManual,allowExternal,validation);return await Definitions.PublishAsync(Company,d.Id,d.Revision);}
        public SubmitPayrollInput Command(PayrollInputDefinitionDto d,PayrollInputValue value,string key)=>new(Company,Subject,Period,Jan1,value,PayrollInputSourceType.MANUAL,key,d.Id);
        public ValueTask<PayrollInputLedgerEntryDto> Submit(PayrollInputDefinitionDto d,PayrollInputValue value,string key)=>Ledger.SubmitAsync(Command(d,value,key));
    }
    private sealed record Context(CompanyId CompanyId):ICompanyContext;
    private sealed class User:ICurrentUser{public UserId UserId{get;}=UserId.From(Guid.NewGuid());public bool HasPermission(string permissionCode)=>true;}
    private sealed class Correlation:ICorrelationContext{public string CorrelationId=>"test-correlation";public string? IdempotencyKey=>null;}
    private sealed class SubjectReader:IPayrollSubjectScopeReader{public Dictionary<PayrollSubjectId,CompanyId> Owners{get;}=[];public CompanyId? FindCompany(PayrollSubjectId id)=>Owners.TryGetValue(id,out var company)?company:null;}
    private sealed class AuditWriter:IAuditWriter{public List<AuditEntry> Entries{get;}=[];public ValueTask WriteAsync(AuditEntry entry,CancellationToken cancellationToken=default){Entries.Add(entry);return ValueTask.CompletedTask;}}
}
