using System.Globalization;
using PayCalc24.Contracts.Diagnostics;
using PayCalc24.Contracts.FormulaRepository;
using PayCalc24.Contracts.Identity;
using PayCalc24.Contracts.Operations;
using PayCalc24.Contracts.Temporal;
using PayCalc24.FormulaRepository.Model;
using PayCalc24.FormulaRepository.Services;

namespace PayCalc24.ApplicationTests;

public sealed class Task07FormulaRepositoryTests
{
    private static readonly DateOnly Jan1=new(2027,1,1),Jul1=new(2027,7,1);
    [Fact] public async Task FormulaLifecycleIsExplicitAndPublishedContentIsImmutable(){var f=new Fixture();var (d,v)=await f.Draft("P3_ELIGIBLE",new(Jan1,null));await f.Publish(v.Id);Assert.Equal(FormulaLifecycleStatus.PUBLISHED,f.Formulas.ResolveEffective(f.Company,d.Code,Jan1).LifecycleStatus);var ex=await Assert.ThrowsAsync<FormulaRepositoryValidationException>(async()=>await f.Formulas.UpdateDraftVersionAsync(f.Company,v.Id,"changed",null,new(Jan1,null)));Assert.Equal(DiagnosticCodes.FormulaPublishedVersionImmutable,ex.Diagnostic.Code);}
    [Fact] public async Task InvalidLifecycleJumpAndPublishedOverlapAreRejected(){var f=new Fixture();var (d,v1)=await f.Draft("POLICY",new(Jan1,null));var jump=await Assert.ThrowsAsync<FormulaRepositoryValidationException>(async()=>await f.Formulas.TransitionAsync(f.Company,v1.Id,FormulaLifecycleStatus.PUBLISHED));Assert.Equal(DiagnosticCodes.FormulaInvalidLifecycleTransition,jump.Diagnostic.Code);await f.Publish(v1.Id);var v2=await f.Formulas.CreateDraftVersionAsync(f.Company,d.Id,"2",new(Jul1,null));await f.Advance(v2.Id,FormulaLifecycleStatus.APPROVED);var overlap=await Assert.ThrowsAsync<FormulaRepositoryValidationException>(async()=>await f.Formulas.TransitionAsync(f.Company,v2.Id,FormulaLifecycleStatus.PUBLISHED));Assert.Equal(DiagnosticCodes.FormulaPublishedVersionOverlap,overlap.Diagnostic.Code);}
    [Fact] public async Task HalfOpenFormulaResolutionPreservesHistory(){var f=new Fixture();var (d,v1)=await f.Draft("RATE",new(Jan1,Jul1));await f.Publish(v1.Id);var v2=await f.Formulas.CreateDraftVersionAsync(f.Company,d.Id,"2",new(Jul1,null));await f.AddRequiredTest(v2.Id);await f.Publish(v2.Id);Assert.Equal(1,f.Formulas.ResolveEffective(f.Company,"RATE",Jan1).Revision);Assert.Equal(2,f.Formulas.ResolveEffective(f.Company,"RATE",Jul1).Revision);Assert.Equal(2,f.Formulas.GetVersionHistory(f.Company,d.Id).Count);}
    [Fact] public async Task DuplicateSelfCrossCompanyAndCircularDependenciesAreRejected(){var f=new Fixture();var (a,av)=await f.Draft("A",new(Jan1,null));var (b,bv)=await f.Draft("B",new(Jan1,null));var (c,cv)=await f.Draft("C",new(Jan1,null));await f.Formulas.AddDependencyAsync(f.Company,av.Id,FormulaDependencyType.FORMULA,b.Code,b.Id.Value);await f.Formulas.AddDependencyAsync(f.Company,bv.Id,FormulaDependencyType.FORMULA,c.Code,c.Id.Value);var cycle=await Assert.ThrowsAsync<FormulaRepositoryValidationException>(async()=>await f.Formulas.AddDependencyAsync(f.Company,cv.Id,FormulaDependencyType.FORMULA,a.Code,a.Id.Value));Assert.Equal(DiagnosticCodes.FormulaCircularDependency,cycle.Diagnostic.Code);var self=await Assert.ThrowsAsync<FormulaRepositoryValidationException>(async()=>await f.Formulas.AddDependencyAsync(f.Company,av.Id,FormulaDependencyType.FORMULA,a.Code,a.Id.Value));Assert.Equal(DiagnosticCodes.FormulaSelfDependency,self.Diagnostic.Code);}
    [Fact] public async Task DependenciesAndTestCasesAreMetadataAndFreezeAtPublication(){var f=new Fixture();var (_,v)=await f.Draft("TOTAL",new(Jan1,null));await f.Formulas.AddDependencyAsync(f.Company,v.Id,FormulaDependencyType.INPUT,"NET_REVENUE");await f.Formulas.AddDependencyAsync(f.Company,v.Id,FormulaDependencyType.PARAMETER,"SALES_RATE");await f.Formulas.AddDependencyAsync(f.Company,v.Id,FormulaDependencyType.LOOKUP,"SALES_TIER");await f.Formulas.AddTestCaseAsync(f.Company,v.Id,"expected","{\"NET_REVENUE\":100}",FormulaTypedValue.Decimal(10));await f.Publish(v.Id);Assert.Equal(3,f.Formulas.ListDependencies(f.Company,v.Id).Count);Assert.Equal(2,f.Formulas.ListTestCases(f.Company,v.Id).Count);await Assert.ThrowsAsync<FormulaRepositoryValidationException>(async()=>await f.Formulas.AddTestCaseAsync(f.Company,v.Id,"rewrite","{}",FormulaTypedValue.Decimal(0)));Assert.NotNull(f.Formulas.GetVersionHistory(f.Company,v.FormulaDefinitionId).Single().Checksum);}
    [Fact] public void ParameterVersionsPreserveDecimalAndTypedValues(){var f=new Fixture();var v1=f.Policy.CreateParameterDraft(f.Company,"P3_POLICY","P3",null,new(Jan1,Jul1));f.Policy.SetParameterValue(f.Company,v1.Id,"ACHIEVEMENT_FLOOR",FormulaTypedValue.Decimal(.70m));f.Policy.SetParameterValue(f.Company,v1.Id,"ENABLED",FormulaTypedValue.Boolean(true));f.Policy.SetParameterValue(f.Company,v1.Id,"COUNT",FormulaTypedValue.Integer(3));f.Policy.SetParameterValue(f.Company,v1.Id,"DATE",FormulaTypedValue.Date(Jan1));f.Policy.SetParameterValue(f.Company,v1.Id,"LABEL",FormulaTypedValue.Text("P3"));f.PublishParameter(v1.Id);var v2=f.Policy.CreateParameterDraft(f.Company,"P3_POLICY","P3",null,new(Jul1,null));f.Policy.SetParameterValue(f.Company,v2.Id,"ACHIEVEMENT_FLOOR",FormulaTypedValue.Decimal(.75m));f.PublishParameter(v2.Id);Assert.Equal(.70m,f.Policy.ResolveParameterSet(f.Company,"P3_POLICY",Jan1).Values.Single(x=>x.Code=="ACHIEVEMENT_FLOOR").Value.DecimalValue);Assert.Equal(.75m,f.Policy.ResolveParameterSet(f.Company,"P3_POLICY",Jul1).Values.Single().Value.DecimalValue);}
    [Fact] public void LookupRowsAreValidatedOrderedVersionedAndImmutable(){var f=new Fixture();var table=f.Policy.CreateLookupDraft(f.Company,"ACHIEVEMENT_FACTOR","Factor",FormulaDataType.INTEGER,FormulaDataType.DECIMAL,LookupMatchType.EXACT,new(Jan1,null));f.Policy.AddLookupRow(f.Company,table.Id,2,FormulaTypedValue.Integer(80),null,null,FormulaTypedValue.Decimal(.70m));var updated=f.Policy.AddLookupRow(f.Company,table.Id,1,FormulaTypedValue.Integer(70),null,null,FormulaTypedValue.Decimal(.50m));Assert.Equal([1,2],updated.Rows.Select(x=>x.Sequence));Assert.Throws<FormulaRepositoryValidationException>(()=>f.Policy.AddLookupRow(f.Company,table.Id,3,FormulaTypedValue.Integer(70),null,null,FormulaTypedValue.Decimal(.6m)));f.PublishLookup(table.Id);Assert.Throws<FormulaRepositoryValidationException>(()=>f.Policy.AddLookupRow(f.Company,table.Id,3,FormulaTypedValue.Integer(90),null,null,FormulaTypedValue.Decimal(.85m)));}
    [Fact] public void RuleSetOrderingElseAndImmutabilityAreStructuralOnly(){var f=new Fixture();var set=f.Policy.CreateRuleSetDraft(f.Company,"ATTENDANCE_SCORE","Attendance",FormulaDataType.DECIMAL,FormulaScopeType.EMPLOYEE,new(Jan1,null),true);f.Policy.AddRule(f.Company,set.Id,2,"UnauthorizedLeave = 1","0.70");f.Policy.AddRule(f.Company,set.Id,1,"UnauthorizedLeave >= 2","0");var updated=f.Policy.AddRule(f.Company,set.Id,3,null,"1.00",true);Assert.Equal([1,2,3],updated.Rules.Select(x=>x.Priority));Assert.Throws<FormulaRepositoryValidationException>(()=>f.Policy.AddRule(f.Company,set.Id,4,null,".5",true));f.PublishRuleSet(set.Id);Assert.Throws<FormulaRepositoryValidationException>(()=>f.Policy.AddRule(f.Company,set.Id,4,"LateCount > 3",".9"));}
    [Theory][InlineData("en-US")][InlineData("vi-VN")]public async Task CanonicalCodesAreCultureIndependentAndTwoCompaniesUseSameModel(string culture){var old=CultureInfo.CurrentCulture;try{CultureInfo.CurrentCulture=new(culture);var a=new Fixture();var (ad,_)=await a.Draft("p3_eligible",new(Jan1,null));var b=new Fixture();var (bd,_)=await b.Draft("sales_incentive",new(Jan1,null));Assert.Equal("P3_ELIGIBLE",ad.Code);Assert.Equal("SALES_INCENTIVE",bd.Code);}finally{CultureInfo.CurrentCulture=old;}}

    private sealed class Fixture
    {
        public CompanyId Company{get;}=CompanyId.From(Guid.NewGuid());public FormulaRepositoryService Formulas{get;}public PolicyRepositoryService Policy{get;}public Fixture(){var c=new Context(Company);Formulas=new(c,new User(),new Correlation(),new Audit(),TimeProvider.System);Policy=new(c);}public async ValueTask<(FormulaDefinitionDto,FormulaVersionDto)> Draft(string code,EffectivePeriod p){var d=await Formulas.CreateDefinitionAsync(Company,code,code,null,FormulaDataType.DECIMAL,FormulaScopeType.COMPANY);var v=await Formulas.CreateDraftVersionAsync(Company,d.Id,"source text",p);await AddRequiredTest(v.Id);return(d,v);}public ValueTask<FormulaTestCaseDto> AddRequiredTest(FormulaVersionId id)=>Formulas.AddTestCaseAsync(Company,id,"structural","{}",FormulaTypedValue.Decimal(0));public async ValueTask Advance(FormulaVersionId id,FormulaLifecycleStatus through){foreach(var s in new[]{FormulaLifecycleStatus.VALIDATED,FormulaLifecycleStatus.TESTED,FormulaLifecycleStatus.APPROVED}){await Formulas.TransitionAsync(Company,id,s);if(s==through)return;}}public async ValueTask Publish(FormulaVersionId id){await Advance(id,FormulaLifecycleStatus.APPROVED);await Formulas.TransitionAsync(Company,id,FormulaLifecycleStatus.PUBLISHED);}private static readonly FormulaLifecycleStatus[] Stages=[FormulaLifecycleStatus.VALIDATED,FormulaLifecycleStatus.TESTED,FormulaLifecycleStatus.APPROVED,FormulaLifecycleStatus.PUBLISHED];public void PublishParameter(ParameterSetVersionId id){foreach(var s in Stages)Policy.TransitionParameter(Company,id,s);}public void PublishLookup(LookupTableVersionId id){foreach(var s in Stages)Policy.TransitionLookup(Company,id,s);}public void PublishRuleSet(RuleSetVersionId id){foreach(var s in Stages)Policy.TransitionRuleSet(Company,id,s);}
    }
    private sealed record Context(CompanyId CompanyId):ICompanyContext;private sealed class User:ICurrentUser{public UserId UserId{get;}=UserId.From(Guid.NewGuid());public bool HasPermission(string code)=>true;}private sealed class Correlation:ICorrelationContext{public string CorrelationId=>"task-07";public string? IdempotencyKey=>null;}private sealed class Audit:IAuditWriter{public ValueTask WriteAsync(AuditEntry entry,CancellationToken token=default)=>ValueTask.CompletedTask;}
}
