using PayCalc24.Contracts.Diagnostics;
using PayCalc24.Contracts.Compensation;
using PayCalc24.Contracts.Identity;
using PayCalc24.Contracts.Organization;
using PayCalc24.Organization.Model;

namespace PayCalc24.Organization.Services;

public sealed class OrganizationRegistry(ICompanyContext companyContext)
{
    private readonly List<PayrollSubject> subjects=[]; private readonly List<OrganizationUnit> units=[]; private readonly List<Position> positions=[]; private readonly List<JobGrade> grades=[]; private readonly List<PayrollAssignment> assignments=[];
    private void Scope(CompanyId companyId) { if(companyId!=companyContext.CompanyId) Throw(DiagnosticCodes.CompanyScopeMismatch, new(){["requestedCompanyId"]=companyId.Value,["currentCompanyId"]=companyContext.CompanyId.Value}); }
    public void AddSubject(PayrollSubject subject) { Scope(subject.CompanyId); if(subjects.Any(x=>x.CompanyId==subject.CompanyId && StringComparer.OrdinalIgnoreCase.Equals(x.EmployeeCode,subject.EmployeeCode))) Throw(DiagnosticCodes.DuplicateEmployeeCode,new(){["employeeCode"]=subject.EmployeeCode}); subjects.Add(subject); }
    public void AddDependent(PayrollSubject subject, EmployeeDependent dependent) { Scope(subject.CompanyId); Scope(dependent.CompanyId); if(subject.Id!=dependent.PayrollSubjectId || subject.CompanyId!=dependent.CompanyId) InvalidReference("dependent"); subject.AddDependent(dependent); }
    public int GetEligibleDependentCount(CompanyId companyId, PayrollSubjectId subjectId, DateOnly businessDate) { Scope(companyId); var subject=subjects.SingleOrDefault(x=>x.Id==subjectId && x.CompanyId==companyId) ?? throw NotFound("payrollSubject"); return subject.Dependents.Count(x=>x.IsEligible(businessDate)); }
    public void AddUnit(OrganizationUnit unit) { Scope(unit.CompanyId); EnsureParent(unit.CompanyId,unit.Id,unit.ParentId); if(units.Any(x=>x.CompanyId==unit.CompanyId && StringComparer.OrdinalIgnoreCase.Equals(x.Code,unit.Code))) InvalidReference("unitCode"); units.Add(unit); }
    public void ReparentUnit(CompanyId companyId, OrganizationUnitId unitId, OrganizationUnitId? parentId) { Scope(companyId); var unit=units.SingleOrDefault(x=>x.Id==unitId&&x.CompanyId==companyId)??throw NotFound("organizationUnit"); EnsureParent(companyId,unitId,parentId); unit.Reparent(parentId); }
    private void EnsureParent(CompanyId companyId, OrganizationUnitId childId, OrganizationUnitId? parentId) { if(parentId is null)return; var parent=units.SingleOrDefault(x=>x.Id==parentId.Value); if(parent is null || parent.CompanyId!=companyId) InvalidReference("parentOrganizationUnit"); var cursor=parent; var seen=new HashSet<OrganizationUnitId>{childId}; while(cursor is not null){ if(!seen.Add(cursor.Id)) Throw(DiagnosticCodes.OrganizationCycle,new(){["organizationUnitId"]=childId.Value}); cursor=cursor.ParentId is null?null:units.SingleOrDefault(x=>x.Id==cursor.ParentId.Value&&x.CompanyId==companyId); } }
    public void AddPosition(Position position){Scope(position.CompanyId);positions.Add(position);} public void AddJobGrade(JobGrade grade){Scope(grade.CompanyId);grades.Add(grade);}
    public void AddAssignment(PayrollAssignment assignment) { Scope(assignment.CompanyId); if(!subjects.Any(x=>x.Id==assignment.PayrollSubjectId&&x.CompanyId==assignment.CompanyId)||!units.Any(x=>x.Id==assignment.OrganizationUnitId&&x.CompanyId==assignment.CompanyId)||!positions.Any(x=>x.Id==assignment.PositionId&&x.CompanyId==assignment.CompanyId)||(assignment.JobGradeId is not null&&!grades.Any(x=>x.Id==assignment.JobGradeId.Value&&x.CompanyId==assignment.CompanyId))) InvalidReference("assignment"); var overlap=assignments.Any(x=>x.CompanyId==assignment.CompanyId&&x.PayrollSubjectId==assignment.PayrollSubjectId&&x.IsPrimary&&assignment.IsPrimary&&x.Status==RecordStatus.ACTIVE&&assignment.Status==RecordStatus.ACTIVE&&x.EffectivePeriod.Overlaps(assignment.EffectivePeriod)); if(overlap) Throw(DiagnosticCodes.PrimaryAssignmentOverlap,new(){["payrollSubjectId"]=assignment.PayrollSubjectId.Value}); assignments.Add(assignment); }
    public PayrollAssignment ResolvePrimaryAssignment(CompanyId companyId, PayrollSubjectId subjectId, DateOnly businessDate) { Scope(companyId); var matches=assignments.Where(x=>x.CompanyId==companyId&&x.PayrollSubjectId==subjectId&&x.IsPrimary&&x.Status==RecordStatus.ACTIVE&&x.EffectivePeriod.Contains(businessDate)).ToArray(); if(matches.Length==0)throw NotFound("payrollAssignment"); if(matches.Length>1)Throw(DiagnosticCodes.PrimaryAssignmentOverlap,new(){["payrollSubjectId"]=subjectId.Value,["matchCount"]=matches.Length}); return matches[0]; }
    public IReadOnlyList<PayrollAssignment> GetAssignmentHistory(CompanyId companyId, PayrollSubjectId subjectId){Scope(companyId);return assignments.Where(x=>x.CompanyId==companyId&&x.PayrollSubjectId==subjectId).OrderBy(x=>x.EffectivePeriod.EffectiveFrom).ToArray();}
    public void SetCompensationScheme(PayrollAssignment assignment, CompensationSchemeDto scheme)
    { Scope(assignment.CompanyId); if(assignment.CompanyId!=scheme.CompanyId)Throw(DiagnosticCodes.InvalidAssignmentSchemeScope,new(){["assignmentId"]=assignment.Id.Value,["schemeId"]=scheme.Id.Value}); assignment.SetCompensationScheme(scheme.Id); }
    private static void InvalidReference(string reference)=>Throw(DiagnosticCodes.InvalidOrganizationReference,new(){["reference"]=reference}); private static OrganizationValidationException NotFound(string entity)=>new(new(DiagnosticCodes.AssignmentNotFound,DiagnosticSeverity.Error,new Dictionary<string,object?>{{"entity",entity}})); private static void Throw(string code,Dictionary<string,object?> args)=>throw new OrganizationValidationException(new(code,DiagnosticSeverity.Error,args));
}
