using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using PayCalc24.Contracts.Diagnostics;
using PayCalc24.Contracts.FormulaRepository;
using PayCalc24.Contracts.Identity;
using PayCalc24.Contracts.Operations;
using PayCalc24.Contracts.Temporal;
using PayCalc24.FormulaRepository.Model;

namespace PayCalc24.FormulaRepository.Services;

public sealed class FormulaRepositoryService(ICompanyContext companyContext,ICurrentUser currentUser,ICorrelationContext correlationContext,IAuditWriter auditWriter,TimeProvider timeProvider):IFormulaRepositoryService
{
    private readonly List<FormulaDefinition> definitions=[];
    public async ValueTask<FormulaDefinitionDto> CreateDefinitionAsync(CompanyId companyId,string code,string name,string? description,FormulaDataType returnType,FormulaScopeType scopeType,CancellationToken token=default)
    {
        Scope(companyId); code=Code(code); Required(name); if(definitions.Any(x=>x.Definition.CompanyId==companyId&&Eq(x.Definition.Code,code))) Throw(DiagnosticCodes.DuplicateFormulaDefinitionCode,new(){["code"]=code});
        var dto=new FormulaDefinitionDto(FormulaDefinitionId.From(Guid.NewGuid()),companyId,code,name.Trim(),Optional(description),returnType,scopeType,true);definitions.Add(new(dto));await Audit(dto.CompanyId,FormulaRepositoryAuditActions.DefinitionCreated,"FormulaDefinition",dto.Id.Value,null,token);return dto;
    }
    public async ValueTask<FormulaVersionDto> CreateDraftVersionAsync(CompanyId companyId,FormulaDefinitionId definitionId,string expressionText,EffectivePeriod period,CancellationToken token=default)
    {
        Scope(companyId);ValidatePeriod(period);Required(expressionText);var d=Definition(companyId,definitionId);var revision=d.Versions.Count==0?1:d.Versions.Max(x=>x.Version.Revision)+1;var now=timeProvider.GetUtcNow();var dto=new FormulaVersionDto(FormulaVersionId.From(Guid.NewGuid()),definitionId,companyId,revision,expressionText,null,period,FormulaLifecycleStatus.DRAFT,null,now,currentUser.UserId,null,null,null,null,null,null);d.Versions.Add(new(dto));await Audit(companyId,FormulaRepositoryAuditActions.DraftCreated,"FormulaVersion",dto.Id.Value,revision,token);return dto;
    }
    public async ValueTask<FormulaVersionDto> UpdateDraftVersionAsync(CompanyId companyId,FormulaVersionId versionId,string expressionText,string? expressionAstJson,EffectivePeriod period,CancellationToken token=default)
    {
        Scope(companyId);ValidatePeriod(period);Required(expressionText);var v=Version(companyId,versionId);Mutable(v);v.Version=v.Version with{ExpressionText=expressionText,ExpressionAstJson=Optional(expressionAstJson),EffectivePeriod=period,Checksum=null};await Audit(companyId,FormulaRepositoryAuditActions.DraftUpdated,"FormulaVersion",versionId.Value,v.Version.Revision,token);return v.Version;
    }
    public async ValueTask<FormulaDependencyDto> AddDependencyAsync(CompanyId companyId,FormulaVersionId versionId,FormulaDependencyType type,string referenceCode,Guid? referencedEntityId=null,bool isRequired=true,int? sequence=null,CancellationToken token=default)
    {
        Scope(companyId);var v=Version(companyId,versionId);Mutable(v);referenceCode=Code(referenceCode);if(v.Dependencies.Any(x=>x.DependencyType==type&&Eq(x.ReferenceCode,referenceCode)))Throw(DiagnosticCodes.FormulaDuplicateDependency,new(){["referenceCode"]=referenceCode});
        if(type==FormulaDependencyType.FORMULA){var owner=referencedEntityId is null?definitions.SingleOrDefault(x=>Eq(x.Definition.Code,referenceCode)):definitions.SingleOrDefault(x=>x.Definition.Id.Value==referencedEntityId);if(owner is null)Throw(DiagnosticCodes.FormulaDefinitionNotFound,new(){["referenceCode"]=referenceCode});if(owner!.Definition.CompanyId!=companyId)Throw(DiagnosticCodes.FormulaCrossCompanyReference,[]);if(owner.Definition.Id==v.Version.FormulaDefinitionId)Throw(DiagnosticCodes.FormulaSelfDependency,[]);}
        var dto=new FormulaDependencyDto(Guid.NewGuid(),companyId,versionId,type,referenceCode,referencedEntityId,isRequired,sequence);v.Dependencies.Add(dto);if(HasCycle(companyId)){v.Dependencies.Remove(dto);Throw(DiagnosticCodes.FormulaCircularDependency,[]);}await Audit(companyId,FormulaRepositoryAuditActions.DependencyAdded,"FormulaVersion",versionId.Value,v.Version.Revision,token);return dto;
    }
    public async ValueTask RemoveDependencyAsync(CompanyId companyId,FormulaVersionId versionId,Guid dependencyId,CancellationToken token=default){Scope(companyId);var v=Version(companyId,versionId);Mutable(v);v.Dependencies.RemoveAll(x=>x.Id==dependencyId);await Audit(companyId,FormulaRepositoryAuditActions.DependencyRemoved,"FormulaVersion",versionId.Value,v.Version.Revision,token);}
    public async ValueTask<FormulaTestCaseDto> AddTestCaseAsync(CompanyId companyId,FormulaVersionId versionId,string name,string inputJson,FormulaTypedValue? expectedValue,string? expectedDiagnosticCode=null,bool isRequired=true,decimal? tolerance=null,CancellationToken token=default)
    {Scope(companyId);var v=Version(companyId,versionId);Mutable(v);Required(name);Required(inputJson);if(expectedValue is null&&string.IsNullOrWhiteSpace(expectedDiagnosticCode))throw new ArgumentException("Expected value or diagnostic is required.");if(tolerance is not null&&(expectedValue?.DataType!=FormulaDataType.DECIMAL||tolerance<0))Throw(DiagnosticCodes.InvalidParameterValueType,[]);ValidateValue(expectedValue);var dto=new FormulaTestCaseDto(Guid.NewGuid(),companyId,versionId,name.Trim(),inputJson,expectedValue,expectedValue?.DataType,tolerance,Optional(expectedDiagnosticCode),isRequired,null);v.TestCases.Add(dto);await Audit(companyId,FormulaRepositoryAuditActions.TestCaseChanged,"FormulaVersion",versionId.Value,v.Version.Revision,token);return dto;}
    public async ValueTask UpdateTestCaseAsync(CompanyId companyId,FormulaVersionId versionId,FormulaTestCaseDto testCase,CancellationToken token=default){Scope(companyId);var v=Version(companyId,versionId);Mutable(v);if(testCase.CompanyId!=companyId||testCase.FormulaVersionId!=versionId)Throw(DiagnosticCodes.FormulaCrossCompanyReference,[]);var i=v.TestCases.FindIndex(x=>x.Id==testCase.Id);if(i<0)Throw(DiagnosticCodes.FormulaVersionNotFound,[]);ValidateValue(testCase.ExpectedValue);v.TestCases[i]=testCase;await Audit(companyId,FormulaRepositoryAuditActions.TestCaseChanged,"FormulaVersion",versionId.Value,v.Version.Revision,token);}
    public async ValueTask RemoveTestCaseAsync(CompanyId companyId,FormulaVersionId versionId,Guid testCaseId,CancellationToken token=default){Scope(companyId);var v=Version(companyId,versionId);Mutable(v);v.TestCases.RemoveAll(x=>x.Id==testCaseId);await Audit(companyId,FormulaRepositoryAuditActions.TestCaseChanged,"FormulaVersion",versionId.Value,v.Version.Revision,token);}
    public async ValueTask<FormulaVersionDto> TransitionAsync(CompanyId companyId,FormulaVersionId versionId,FormulaLifecycleStatus target,CancellationToken token=default)
    {
        Scope(companyId);var v=Version(companyId,versionId);var expected=v.Version.LifecycleStatus switch{FormulaLifecycleStatus.DRAFT=>FormulaLifecycleStatus.VALIDATED,FormulaLifecycleStatus.VALIDATED=>FormulaLifecycleStatus.TESTED,FormulaLifecycleStatus.TESTED=>FormulaLifecycleStatus.APPROVED,FormulaLifecycleStatus.APPROVED=>FormulaLifecycleStatus.PUBLISHED,FormulaLifecycleStatus.PUBLISHED=>FormulaLifecycleStatus.RETIRED,_=>(FormulaLifecycleStatus?)null};if(expected!=target)Throw(DiagnosticCodes.FormulaInvalidLifecycleTransition,new(){["current"]=v.Version.LifecycleStatus,["target"]=target});var now=timeProvider.GetUtcNow();
        if(target==FormulaLifecycleStatus.PUBLISHED){var d=Definition(companyId,v.Version.FormulaDefinitionId);if(d.Versions.Any(x=>x!=v&&x.Version.LifecycleStatus==FormulaLifecycleStatus.PUBLISHED&&x.Version.EffectivePeriod.Overlaps(v.Version.EffectivePeriod)))Throw(DiagnosticCodes.FormulaPublishedVersionOverlap,[]);if(!v.TestCases.Any(x=>x.IsRequired))Throw(DiagnosticCodes.FormulaRequiredTestCaseMissing,[]);v.Version=v.Version with{Checksum=Checksum(v),PublishedAt=now,PublishedBy=currentUser.UserId};}
        v.Version=target switch{FormulaLifecycleStatus.VALIDATED=>v.Version with{LifecycleStatus=target,ValidatedAt=now},FormulaLifecycleStatus.TESTED=>v.Version with{LifecycleStatus=target,TestedAt=now},FormulaLifecycleStatus.APPROVED=>v.Version with{LifecycleStatus=target,ApprovedAt=now},FormulaLifecycleStatus.RETIRED=>v.Version with{LifecycleStatus=target,RetiredAt=now},_=>v.Version with{LifecycleStatus=target}};var action=target switch{FormulaLifecycleStatus.VALIDATED=>FormulaRepositoryAuditActions.Validated,FormulaLifecycleStatus.TESTED=>FormulaRepositoryAuditActions.Tested,FormulaLifecycleStatus.APPROVED=>FormulaRepositoryAuditActions.Approved,FormulaLifecycleStatus.PUBLISHED=>FormulaRepositoryAuditActions.Published,FormulaLifecycleStatus.RETIRED=>FormulaRepositoryAuditActions.Retired,_=>FormulaRepositoryAuditActions.DraftUpdated};await Audit(companyId,action,"FormulaVersion",versionId.Value,v.Version.Revision,token);return v.Version;
    }
    public IReadOnlyList<FormulaDefinitionDto> ListDefinitions(CompanyId companyId,string? search=null){Scope(companyId);return definitions.Where(x=>x.Definition.CompanyId==companyId&&(string.IsNullOrWhiteSpace(search)||x.Definition.Code.Contains(search,StringComparison.OrdinalIgnoreCase)||x.Definition.Name.Contains(search,StringComparison.OrdinalIgnoreCase))).Select(x=>x.Definition).OrderBy(x=>x.Code,StringComparer.OrdinalIgnoreCase).ToArray();}
    public IReadOnlyList<FormulaVersionDto> GetVersionHistory(CompanyId companyId,FormulaDefinitionId definitionId){Scope(companyId);return Definition(companyId,definitionId).Versions.Select(x=>x.Version).OrderBy(x=>x.Revision).ToArray();}
    public FormulaVersionDto ResolveEffective(CompanyId companyId,string code,DateOnly businessDate){Scope(companyId);var matches=definitions.Where(x=>x.Definition.CompanyId==companyId&&Eq(x.Definition.Code,code)).SelectMany(x=>x.Versions).Where(x=>x.Version.LifecycleStatus==FormulaLifecycleStatus.PUBLISHED&&x.Version.EffectivePeriod.Contains(businessDate)).ToArray();if(matches.Length!=1)Throw(matches.Length==0?DiagnosticCodes.FormulaEffectiveVersionNotFound:DiagnosticCodes.FormulaEffectiveVersionAmbiguous,new(){["code"]=code,["businessDate"]=businessDate,["matchCount"]=matches.Length});return matches[0].Version;}
    public IReadOnlyList<FormulaDependencyDto> ListDependencies(CompanyId companyId,FormulaVersionId versionId){Scope(companyId);return Version(companyId,versionId).Dependencies.OrderBy(x=>x.Sequence??int.MaxValue).ThenBy(x=>x.ReferenceCode,StringComparer.Ordinal).ToArray();}
    public IReadOnlyList<FormulaTestCaseDto> ListTestCases(CompanyId companyId,FormulaVersionId versionId){Scope(companyId);return Version(companyId,versionId).TestCases.ToArray();}
    private bool HasCycle(CompanyId c){var edges=definitions.Where(x=>x.Definition.CompanyId==c).ToDictionary(x=>x.Definition.Id,x=>x.Versions.SelectMany(v=>v.Dependencies).Where(d=>d.DependencyType==FormulaDependencyType.FORMULA).Select(d=>definitions.SingleOrDefault(z=>z.Definition.CompanyId==c&&(d.ReferencedEntityId==z.Definition.Id.Value||Eq(d.ReferenceCode,z.Definition.Code)))?.Definition.Id).Where(x=>x is not null).Select(x=>x!.Value).ToArray());var visiting=new HashSet<FormulaDefinitionId>();var visited=new HashSet<FormulaDefinitionId>();bool Visit(FormulaDefinitionId n){if(!visiting.Add(n))return true;if(visited.Contains(n)){visiting.Remove(n);return false;}foreach(var next in edges.GetValueOrDefault(n,[]))if(Visit(next))return true;visiting.Remove(n);visited.Add(n);return false;}return edges.Keys.Any(Visit);}
    private FormulaDefinition Definition(CompanyId c,FormulaDefinitionId id){var x=definitions.SingleOrDefault(x=>x.Definition.Id==id);if(x is not null&&x.Definition.CompanyId!=c)Throw(DiagnosticCodes.FormulaCrossCompanyReference,[]);return x??throw Error(DiagnosticCodes.FormulaDefinitionNotFound,new(){["definitionId"]=id.Value});}
    private FormulaVersion Version(CompanyId c,FormulaVersionId id){var x=definitions.SelectMany(x=>x.Versions).SingleOrDefault(x=>x.Version.Id==id);if(x is not null&&x.Version.CompanyId!=c)Throw(DiagnosticCodes.FormulaCrossCompanyReference,[]);return x??throw Error(DiagnosticCodes.FormulaVersionNotFound,new(){["versionId"]=id.Value});}
    private static void Mutable(FormulaVersion v){if(v.Version.LifecycleStatus!=FormulaLifecycleStatus.DRAFT)Throw(DiagnosticCodes.FormulaPublishedVersionImmutable,new(){["status"]=v.Version.LifecycleStatus});}
    private static string Checksum(FormulaVersion v){var content=string.Join('\n',new[]{v.Version.ExpressionText,v.Version.EffectivePeriod.EffectiveFrom.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture),v.Version.EffectivePeriod.EffectiveTo?.ToString("yyyy-MM-dd",CultureInfo.InvariantCulture)??"",v.Version.Revision.ToString(CultureInfo.InvariantCulture)}.Concat(v.Dependencies.OrderBy(x=>x.Sequence??int.MaxValue).ThenBy(x=>x.DependencyType).ThenBy(x=>x.ReferenceCode,StringComparer.Ordinal).Select(x=>$"{x.DependencyType}|{x.ReferenceCode}|{x.ReferencedEntityId:D}|{x.IsRequired}|{x.Sequence}")));return Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content)));}
    private async ValueTask Audit(CompanyId c,string action,string entity,Guid id,int? revision,CancellationToken token)=>await auditWriter.WriteAsync(new(c,currentUser.UserId,action,entity,id.ToString("D"),correlationContext.CorrelationId,timeProvider.GetUtcNow(),revision is null?[]:new Dictionary<string,object?>{{"revision",revision}}),token);
    private void Scope(CompanyId c){if(c!=companyContext.CompanyId)Throw(DiagnosticCodes.CompanyScopeMismatch,[]);} internal static void ValidatePeriod(EffectivePeriod p){if(p.EffectiveTo is not null&&p.EffectiveFrom>=p.EffectiveTo)Throw(DiagnosticCodes.InvalidEffectiveRange,[]);} internal static void ValidateValue(FormulaTypedValue? v){if(v is null)return;var count=new object?[]{v.DecimalValue,v.IntegerValue,v.BooleanValue,v.DateValue,v.TextValue}.Count(x=>x is not null);var valid=v.DataType switch{FormulaDataType.DECIMAL=>v.DecimalValue is not null,FormulaDataType.INTEGER=>v.IntegerValue is not null,FormulaDataType.BOOLEAN=>v.BooleanValue is not null,FormulaDataType.DATE=>v.DateValue is not null,FormulaDataType.TEXT=>v.TextValue is not null,_=>false};if(count!=1||!valid)Throw(DiagnosticCodes.InvalidParameterValueType,[]);} internal static string Code(string s){Required(s);return s.Trim().ToUpperInvariant();} internal static void Required(string s){if(string.IsNullOrWhiteSpace(s))throw new ArgumentException("Value is required.");} internal static string? Optional(string? s)=>string.IsNullOrWhiteSpace(s)?null:s.Trim(); internal static bool Eq(string a,string b)=>StringComparer.OrdinalIgnoreCase.Equals(a.Trim(),b.Trim()); internal static FormulaRepositoryValidationException Error(string code,Dictionary<string,object?> args)=>new(new(code,DiagnosticSeverity.Error,args)); internal static void Throw(string code,Dictionary<string,object?> args)=>throw Error(code,args);
}
