using PayCalc24.Contracts.Diagnostics;
using PayCalc24.Contracts.FormulaRepository;
using PayCalc24.Contracts.Identity;
using PayCalc24.Contracts.Temporal;
using PayCalc24.FormulaRepository.Model;
using static PayCalc24.FormulaRepository.Services.FormulaRepositoryService;

namespace PayCalc24.FormulaRepository.Services;

public sealed class PolicyRepositoryService(ICompanyContext companyContext):IPolicyRepositoryService
{
    private readonly List<ParameterSetVersion> parameters=[]; private readonly List<LookupTableVersion> lookups=[]; private readonly List<RuleSetVersion> ruleSets=[];
    public ParameterSetVersionDto CreateParameterDraft(CompanyId companyId,string code,string name,string? description,EffectivePeriod period){Scope(companyId);ValidatePeriod(period);code=Code(code);Required(name);var revision=Next(parameters.Select(x=>x.Version),(x)=>x.CompanyId==companyId&&Eq(x.Code,code),x=>x.Revision,DiagnosticCodes.DuplicateParameterSetCode);var dto=new ParameterSetVersionDto(ParameterSetVersionId.From(Guid.NewGuid()),companyId,code,name.Trim(),Optional(description),revision,period,FormulaLifecycleStatus.DRAFT,[]);parameters.Add(new(dto));return dto;}
    public ParameterSetVersionDto SetParameterValue(CompanyId companyId,ParameterSetVersionId versionId,string code,FormulaTypedValue value,string? unitType=null,string? name=null){Scope(companyId);var v=Parameter(companyId,versionId);Draft(v.Version.LifecycleStatus,DiagnosticCodes.PublishedParameterSetImmutable);ValidateValue(value);code=Code(code);var current=v.Values.SingleOrDefault(x=>Eq(x.Code,code));var dto=new ParameterValueDto(current?.Id??Guid.NewGuid(),companyId,versionId,code,Optional(name),value,Optional(unitType),null,current?.DisplayOrder);if(current is not null)v.Values.Remove(current);v.Values.Add(dto);return ParameterDto(v);}
    public ParameterSetVersionDto TransitionParameter(CompanyId companyId,ParameterSetVersionId versionId,FormulaLifecycleStatus target){Scope(companyId);var v=Parameter(companyId,versionId);CheckTransition(v.Version.LifecycleStatus,target);CheckOverlap(target,v.Version.EffectivePeriod,parameters.Where(x=>x!=v).Select(x=>x.Version).Where(x=>x.CompanyId==companyId&&Eq(x.Code,v.Version.Code)).Select(x=>(x.LifecycleStatus,x.EffectivePeriod)));v.Version=v.Version with{LifecycleStatus=target};return ParameterDto(v);}
    public ParameterSetVersionDto ResolveParameterSet(CompanyId companyId,string code,DateOnly businessDate){Scope(companyId);var x=Resolve(parameters.Select(x=>x.Version),companyId,code,businessDate,x=>x.CompanyId,x=>x.Code,x=>x.EffectivePeriod,x=>x.LifecycleStatus,DiagnosticCodes.EffectiveParameterSetNotFound);return ParameterDto(parameters.Single(v=>v.Version.Id==x.Id));}
    public LookupTableVersionDto CreateLookupDraft(CompanyId companyId,string code,string name,FormulaDataType keyType,FormulaDataType valueType,LookupMatchType matchType,EffectivePeriod period,bool allowRangeOverlap=false){Scope(companyId);ValidatePeriod(period);code=Code(code);Required(name);var revision=Next(lookups.Select(x=>x.Version),x=>x.CompanyId==companyId&&Eq(x.Code,code),x=>x.Revision,DiagnosticCodes.DuplicateLookupTableCode);var dto=new LookupTableVersionDto(LookupTableVersionId.From(Guid.NewGuid()),companyId,code,name.Trim(),null,keyType,valueType,matchType,allowRangeOverlap,revision,period,FormulaLifecycleStatus.DRAFT,[]);lookups.Add(new(dto));return dto;}
    public LookupTableVersionDto AddLookupRow(CompanyId companyId,LookupTableVersionId versionId,int sequence,FormulaTypedValue? key,FormulaTypedValue? lower,FormulaTypedValue? upper,FormulaTypedValue result){Scope(companyId);var v=Lookup(companyId,versionId);Draft(v.Version.LifecycleStatus,DiagnosticCodes.PublishedLookupTableImmutable);ValidateValue(key);ValidateValue(lower);ValidateValue(upper);ValidateValue(result);if(result.DataType!=v.Version.ValueDataType||(key??lower??upper)?.DataType!=v.Version.KeyDataType)Throw(DiagnosticCodes.InvalidParameterValueType,[]);if(v.Rows.Any(x=>x.Sequence==sequence))Throw(DiagnosticCodes.DuplicateLookupSequence,[]);if(v.Version.MatchType==LookupMatchType.EXACT){if(key is null)Throw(DiagnosticCodes.InvalidLookupRange,[]);if(v.Rows.Any(x=>ValueEquals(x.KeyValue,key)))Throw(DiagnosticCodes.DuplicateLookupKey,[]);}else{if(lower is null||upper is null||Compare(lower,upper)>0)Throw(DiagnosticCodes.InvalidLookupRange,[]);if(!v.Version.AllowRangeOverlap&&v.Rows.Any(x=>x.LowerBound is not null&&x.UpperBound is not null&&Compare(lower!,x.UpperBound)<=0&&Compare(x.LowerBound,upper!)<=0))Throw(DiagnosticCodes.OverlappingLookupRange,[]);}v.Rows.Add(new(Guid.NewGuid(),companyId,versionId,sequence,key,lower,upper,result,null,null));return LookupDto(v);}
    public LookupTableVersionDto TransitionLookup(CompanyId companyId,LookupTableVersionId versionId,FormulaLifecycleStatus target){Scope(companyId);var v=Lookup(companyId,versionId);CheckTransition(v.Version.LifecycleStatus,target);CheckOverlap(target,v.Version.EffectivePeriod,lookups.Where(x=>x!=v).Select(x=>x.Version).Where(x=>x.CompanyId==companyId&&Eq(x.Code,v.Version.Code)).Select(x=>(x.LifecycleStatus,x.EffectivePeriod)));v.Version=v.Version with{LifecycleStatus=target};return LookupDto(v);}
    public LookupTableVersionDto ResolveLookup(CompanyId companyId,string code,DateOnly businessDate){Scope(companyId);var x=Resolve(lookups.Select(x=>x.Version),companyId,code,businessDate,x=>x.CompanyId,x=>x.Code,x=>x.EffectivePeriod,x=>x.LifecycleStatus,DiagnosticCodes.FormulaEffectiveVersionNotFound);return LookupDto(lookups.Single(v=>v.Version.Id==x.Id));}
    public RuleSetVersionDto CreateRuleSetDraft(CompanyId companyId,string code,string name,FormulaDataType returnType,FormulaScopeType scope,EffectivePeriod period,bool stopOnMatch){Scope(companyId);ValidatePeriod(period);code=Code(code);Required(name);var revision=Next(ruleSets.Select(x=>x.Version),x=>x.CompanyId==companyId&&Eq(x.Code,code),x=>x.Revision,DiagnosticCodes.DuplicateRuleSetCode);var dto=new RuleSetVersionDto(RuleSetVersionId.From(Guid.NewGuid()),companyId,code,name.Trim(),null,returnType,scope,revision,period,FormulaLifecycleStatus.DRAFT,stopOnMatch,[]);ruleSets.Add(new(dto));return dto;}
    public RuleSetVersionDto AddRule(CompanyId companyId,RuleSetVersionId versionId,int priority,string? condition,string result,bool isElse=false){Scope(companyId);var v=RuleSet(companyId,versionId);Draft(v.Version.LifecycleStatus,DiagnosticCodes.PublishedRuleSetImmutable);ArgumentOutOfRangeException.ThrowIfNegative(priority);Required(result);if(!isElse)Required(condition!);if(v.Rules.Any(x=>x.Priority==priority))Throw(DiagnosticCodes.DuplicateRulePriority,[]);if(isElse&&v.Rules.Any(x=>x.IsElse))Throw(DiagnosticCodes.MultipleElseRules,[]);v.Rules.Add(new(Guid.NewGuid(),companyId,versionId,priority,isElse?null:condition!.Trim(),result.Trim(),isElse,null,null));return RuleDto(v);}
    public RuleSetVersionDto TransitionRuleSet(CompanyId companyId,RuleSetVersionId versionId,FormulaLifecycleStatus target){Scope(companyId);var v=RuleSet(companyId,versionId);if(target==FormulaLifecycleStatus.PUBLISHED&&v.Rules.Any(x=>x.IsElse&&x.Priority!=v.Rules.Max(r=>r.Priority)))Throw(DiagnosticCodes.MultipleElseRules,new(){["reason"]="else_must_be_last"});CheckTransition(v.Version.LifecycleStatus,target);CheckOverlap(target,v.Version.EffectivePeriod,ruleSets.Where(x=>x!=v).Select(x=>x.Version).Where(x=>x.CompanyId==companyId&&Eq(x.Code,v.Version.Code)).Select(x=>(x.LifecycleStatus,x.EffectivePeriod)));v.Version=v.Version with{LifecycleStatus=target};return RuleDto(v);}
    public RuleSetVersionDto ResolveRuleSet(CompanyId companyId,string code,DateOnly businessDate){Scope(companyId);var x=Resolve(ruleSets.Select(x=>x.Version),companyId,code,businessDate,x=>x.CompanyId,x=>x.Code,x=>x.EffectivePeriod,x=>x.LifecycleStatus,DiagnosticCodes.FormulaEffectiveVersionNotFound);return RuleDto(ruleSets.Single(v=>v.Version.Id==x.Id));}
    private ParameterSetVersion Parameter(CompanyId c,ParameterSetVersionId id)=>Owned(parameters.SingleOrDefault(x=>x.Version.Id==id),c,x=>x.Version.CompanyId,DiagnosticCodes.EffectiveParameterSetNotFound);private LookupTableVersion Lookup(CompanyId c,LookupTableVersionId id)=>Owned(lookups.SingleOrDefault(x=>x.Version.Id==id),c,x=>x.Version.CompanyId,DiagnosticCodes.FormulaEffectiveVersionNotFound);private RuleSetVersion RuleSet(CompanyId c,RuleSetVersionId id)=>Owned(ruleSets.SingleOrDefault(x=>x.Version.Id==id),c,x=>x.Version.CompanyId,DiagnosticCodes.FormulaEffectiveVersionNotFound);
    private static T Owned<T>(T? value,CompanyId c,Func<T,CompanyId> company,string notFound) where T:class {if(value is null)Throw(notFound,[]);if(company(value!)!=c)Throw(DiagnosticCodes.FormulaCrossCompanyReference,[]);return value!;}
    private static int Next<T>(IEnumerable<T> values,Func<T,bool> same,Func<T,int> revision,string duplicate){var matching=values.Where(same).ToArray();if(matching.Any(x=>revision(x)==1&&matching.Length==1&&false))Throw(duplicate,[]);return matching.Length==0?1:matching.Max(revision)+1;}
    private static void Draft(FormulaLifecycleStatus s,string code){if(s!=FormulaLifecycleStatus.DRAFT)Throw(code,[]);}private static void CheckTransition(FormulaLifecycleStatus status,FormulaLifecycleStatus target){var expected=status switch{FormulaLifecycleStatus.DRAFT=>FormulaLifecycleStatus.VALIDATED,FormulaLifecycleStatus.VALIDATED=>FormulaLifecycleStatus.TESTED,FormulaLifecycleStatus.TESTED=>FormulaLifecycleStatus.APPROVED,FormulaLifecycleStatus.APPROVED=>FormulaLifecycleStatus.PUBLISHED,FormulaLifecycleStatus.PUBLISHED=>FormulaLifecycleStatus.RETIRED,_=>(FormulaLifecycleStatus?)null};if(expected!=target)Throw(DiagnosticCodes.FormulaInvalidLifecycleTransition,[]);}private static void CheckOverlap(FormulaLifecycleStatus target,EffectivePeriod period,IEnumerable<(FormulaLifecycleStatus Status,EffectivePeriod Period)> others){if(target==FormulaLifecycleStatus.PUBLISHED&&others.Any(x=>x.Status==FormulaLifecycleStatus.PUBLISHED&&x.Period.Overlaps(period)))Throw(DiagnosticCodes.FormulaPublishedVersionOverlap,[]);}
    private static T Resolve<T>(IEnumerable<T> values,CompanyId c,string code,DateOnly date,Func<T,CompanyId> company,Func<T,string> getCode,Func<T,EffectivePeriod> period,Func<T,FormulaLifecycleStatus> status,string missing){var found=values.Where(x=>company(x)==c&&Eq(getCode(x),code)&&status(x)==FormulaLifecycleStatus.PUBLISHED&&period(x).Contains(date)).ToArray();if(found.Length!=1)Throw(found.Length==0?missing:DiagnosticCodes.FormulaEffectiveVersionAmbiguous,[]);return found[0];}
    private static ParameterSetVersionDto ParameterDto(ParameterSetVersion v)=>v.Version with{Values=v.Values.OrderBy(x=>x.DisplayOrder??int.MaxValue).ThenBy(x=>x.Code,StringComparer.Ordinal).ToArray()};private static LookupTableVersionDto LookupDto(LookupTableVersion v)=>v.Version with{Rows=v.Rows.OrderBy(x=>x.Sequence).ToArray()};private static RuleSetVersionDto RuleDto(RuleSetVersion v)=>v.Version with{Rules=v.Rules.OrderBy(x=>x.Priority).ToArray()};
    private static bool ValueEquals(FormulaTypedValue? a,FormulaTypedValue? b)=>a==b;private static int Compare(FormulaTypedValue a,FormulaTypedValue b)=>a.DataType switch{FormulaDataType.DECIMAL=>a.DecimalValue!.Value.CompareTo(b.DecimalValue!.Value),FormulaDataType.INTEGER=>a.IntegerValue!.Value.CompareTo(b.IntegerValue!.Value),FormulaDataType.DATE=>a.DateValue!.Value.CompareTo(b.DateValue!.Value),FormulaDataType.TEXT=>string.CompareOrdinal(a.TextValue,b.TextValue),FormulaDataType.BOOLEAN=>a.BooleanValue!.Value.CompareTo(b.BooleanValue!.Value),_=>0};private void Scope(CompanyId c){if(c!=companyContext.CompanyId)Throw(DiagnosticCodes.CompanyScopeMismatch,[]);}
}
